<div class='well' style='margin: 10px 0;'>
	<form class='form form-inlne'>
		<div class=''>
			<label style='width: 50px;'>产品：</label>
			<select name='category' style='width: 100px;'>
			</select>
			<select name='product' style='width: 100px;'>
			</select>
			<label style='width: 50px;'>类型：</label>
			<select name='mission_category' style='width: 100px;'>
			</select>
			<select name='mission_sub_category' style='width: 100px;'>
			</select>
		</div>
		<div class='clearfix' style='clear:both; margin-top: 10px;'>
			<div class='btn-group pull-left period'>
				<button type="button" class="btn btn-info today">今天</button>
				<button type="button" class="btn btn-info yestorday">昨天</button>
				<button type="button" class="btn btn-info last7">最近7天</button>
				<button type="button" class="btn btn-info last30">最近30天</button>
			</div>
			<div class='pull-left' style='width: 400px;'>
				<div class="col-lg-5 input-group date" id="dp3" data-date="12-02-2012" data-date-format="dd-mm-yyyy">
					<input class="datepicker" size="16" type="text" value="12-02-2012" name='from' readonly="">
					<span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
				</div>
				<div class="col-lg-5 input-group date" id="dp3" data-date="12-02-2012" data-date-format="dd-mm-yyyy">
					<input class="datepicker" size="16" type="text" value="12-02-2012" name='to' readonly="">
					<span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
				</div>
			</div>
		</div>
	</form>
</div>