<div id='forminner-mission'>
	<div id='forminner-view'>
	</div>
</div>
<script>
var time_point_list = ['7天以内', '8-30天', '30天-1年', '1年以上']
var huanhuo_reason_list = ['个人原因', '价格原因', '产品原因', '物流原因', '发货原因', '发票原因']	
</script>
<script type='text/template' id='template-formview-2-12'>
<div class='mission-form-inner'>
	<h1>新建任务 - 退还补发 - 换货</h1>
	<div class='form-group'>
		<button type='button' class='mission-type-change'><i class='glyphicon glyphicon-cog'></i>更改任务类型</button>
	</div>

	<form class="form form-horizontal" role="form" >

		<input type='hidden' name='mission_type_id' value='<%=mission_type_id%>' />

		<div class="form-group">
			<label class="col-lg-2" >店铺：</label>
			<div class='col-lg-4'>
				<select name='store' class='col-lg-10' class='store' ></select>
			</div>
			<label class="col-lg-2" for="ipt_wanwan">旺旺：</label>
			<div class='col-lg-4'>
				<input type="text" name='wanwan' class="form-control wanwan" value='<%=wanwan%>'
					id='ipt_wanwan' placeholder="">
			</div>
		</div>

		<div class="form-group">
			<label class="col-lg-2" >订单号：</label>
			<div class='col-lg-10'>
				<input type="text" name='order_num' class="form-control" value='<%=order_num%>'
					placeholder="多个订单号用空格分开">
				<div class='help-block'>多个订单号用空格分开</div>
			</div>
		</div>

		<div class="form-group">
			<label class="col-lg-2" >时间点：</label>
			<div class='col-lg-10'>
				<select name='time_point' class='col-lg-4' >
					<% time_point = 0; _.each(time_point_list, function(val,key) { if( !time_point ) time_point = key %>
						<option value='<%= val %>' <%= typeof(time_point) != 'undefined' && time_point == val ? 'selected' : '' %>><%= val %></option> <% }); %>
				</select>
				<div class='checkbox'>
					<label>
				    	<input type="checkbox" name='earlier_send'> 提前发货
				    </label>
				</div>
			</div>
		</div>

		<div class="form-group">
			<label class="col-lg-2" >换货原因：</label>
			<div class='col-lg-10'>
				<select name='huanhuo_reason' class='col-lg-4' >
					<% huanhuo_reason = 0; _.each(huanhuo_reason_list, function(val,key) { if( !huanhuo_reason ) huanhuo_reason = key %>
						<option value='<%= val %>' <%= typeof(huanhuo_reason) != 'undefined' && huanhuo_reason == val ? 'selected' : '' %>><%= val %></option> <% }); %>
				</select>
			</div>
		</div>

		<div class="form-group">
			<label class="col-lg-2" >具体原因：</label>
			<div class='col-lg-10'>
				<textarea name='detail_reason' class='col-lg-12' rows='2' ></textarea>
			</div>
		</div>

		<div class='split-line'></div>

		<div class="form-group">
			<label class="col-lg-2" >寄回单号：</label>
			<div class='col-lg-10'>
				<input type="text" name='mail_back_num' class="form-control" value='<%=mail_back_num%>'
					 placeholder="">
			</div>
		</div>

		<div class="form-group clearfix">
			<label class="col-lg-2" >原产品：</label>
			<div class='col-lg-10'>
				<select class='col-lg-3' name='send_back_category_id' >
					<% category_id = 0; _.each(category_list, function(val,key) { if( !category_id ) category_id = key %>
						<option value='<%= val.id %>' <%= typeof(category_id) != 'undefined' && category_id == val.category_id ? 'selected' : '' %>>
						<%= val.name %></option> <% }); %>
				</select>
				<select class='col-lg-3' name='send_back_product_id'>
					<% _.each(product_list[category_id], function(val,key) { %>
						<option value='<%= val.id %>' <%= typeof(product_id) != 'undefined' && product_id == val.product_id ? 'selected' : '' %>>
						<%= val.name %></option> <% }); %>
				</select>
				<input name='send_back_cnt' value='1' style='width: 40px;' />
				<button type="button" class='btn btn-success add_send_back_product'>
					<i class='glyphicon glyphicon-plus'></i> 增加
				</button>
				<table class='table list_send_back_product' style='width: 74%'>
				<tbody></tbody></table>
			</div>
		</div>

		<div class='split-line'></div>

		<div class="form-group">
			<label class="col-lg-2" >寄出单号：</label>
			<div class='col-lg-10'>
				<input type="text" name='mail_to_num' class="form-control" value='<%=mail_to_num%>'
					 placeholder="">
			</div>
		</div>

		<div class="form-group">
			<label class="col-lg-2" >地址：</label>
			<div class='col-lg-10'>
				<input type="text" name='mail_to_address' class="form-control" value='<%=mail_to_address%>'
					 placeholder="">
			</div>
		</div>

		<div class="form-group clearfix">
			<label class="col-lg-2" >换出产品：</label>
			<div class='col-lg-10'>
				<select class='col-lg-3' name='send_to_category_id' >
					<% category_id = 0; _.each(category_list, function(val,key) { if( !category_id ) category_id = key %>
						<option value='<%= val.id %>' <%= typeof(category_id) != 'undefined' && category_id == val.category_id ? 'selected' : '' %>>
						<%= val.name %></option> <% }); %>
				</select>
				<select class='col-lg-3' name='send_to_product_id'>
					<% _.each(product_list[category_id], function(val,key) { %>
						<option value='<%= val.id %>' <%= typeof(product_id) != 'undefined' && product_id == val.product_id ? 'selected' : '' %>>
						<%= val.name %></option> <% }); %>
				</select>
				<input name='send_to_cnt' value='1' style='width: 40px;' />
				<button type="button" class='btn btn-success add_send_to_product'>
					<i class='glyphicon glyphicon-plus'></i> 增加
				</button>
				<table class='table list_send_to_product'>
				<tbody></tbody></table>
			</div>
		</div>

		<div class='split-line'></div>

		<div class="form-group fold-controller">
			<label class="col-lg-12" >获取利润：
				<i class='dofold glyphicon glyphicon-chevron-up'></i>
				<i class='dounfold glyphicon glyphicon-chevron-down'></i>
			</label>
		</div>
		<div class='fold-content mchide'>
			<div class="form-group">
				<label class="col-lg-2" >利润金额：</label>
				<div class='col-lg-6'>
					<div class="input-group">
						<input placeholder='' class='col-lg-12' name='profit' value='<%=profit %>' />
						<span class="input-group-addon">元</span>
					</div>
				</div>
			</div>
			<div class="form-group">
				<label class="col-lg-2" >利润原因：</label>
				<div class='col-lg-10'>
					<textarea class='col-lg-12' name='profit_reason' rows='2' ><%=profit_reason %></textarea>
				</div>
			</div>
		</div>

		<br/>

		<div class="form-group fold-controller">
			<label class="col-lg-12">开启返现：
				<i class='dofold glyphicon glyphicon-chevron-up'></i>
				<i class='dounfold glyphicon glyphicon-chevron-down'></i>
			</label>
		</div>
		<div class='fold-content mchide'>
			<div class="form-group">
				<label class="col-lg-2" >返现金额：</label>
				<div class="input-group col-lg-3">
					<input placeholder='' class='col-lg-12' name='drawback' value='<%=drawback %>' />
					<span class="input-group-addon">元</span>
				</div>
				<label class="col-lg-2" >支付宝：</label>
				<input placeholder='' class='col-lg-5' name='drawback_zhifubao' value='<%=drawback_zhifubao %>' />
			</div>
			<div class="form-group">
				<label class="col-lg-2" >返现原因：</label>
				<div class='col-lg-10'>
					<textarea class='col-lg-12' name='drawback_reason' rows='2' ><%=drawback_reason %></textarea>
				</div>
			</div>
		</div>
		<br/>

		<div class="form-group">
			<div class="col-lg-offset-2 col-lg-10">
				<button type="button" class="btn btn-primary draft">保存草稿</button>
				<button type="button" class="btn btn-warning publish">发布</button>
			</div>
		</div>
	</form>
</div>
</script>
<script type='text/template' id='template-formview-2-12-add-product-back'>
	<tr>
		<td>
			<input type='hidden' name='send_product_back[<%=uid%>][category_id]' value='<%=category_id%>'/>
			<input type='hidden' name='send_product_back[<%=uid%>][product_id]' value='<%=product_id%>'/>
			<input type='hidden' name='send_product_back[<%=uid%>][cnt]' value='<%=cnt%>'/>
			<%=category%>	
		</td>
		<td><%=product%></td>
		<td><%=cnt%></td>
		<td><a href='#' class='op delete'><i class='glyphicon glyphicon-remove'></i></a></td>
	</tr>
</script>

<script type='text/template' id='template-formview-2-12-add-product-out'>
	<tr>
		<td>
			<input type='hidden' name='send_product_out[<%=uid%>][category_id]' value='<%=category_id%>'/>
			<input type='hidden' name='send_product_out[<%=uid%>][product_id]' value='<%=product_id%>'/>
			<input type='hidden' name='send_product_out[<%=uid%>][cnt]' value='<%=cnt%>'/>
			<%=category%>	
		</td>
		<td><%=product%></td>
		<td><%=cnt%></td>
		<td><a href='#' class='op delete'><i class='glyphicon glyphicon-remove'></i></a></td>
	</tr>
</script>
