<div id='forminner-mission'>
	<form class="form form-horizontal" role="form" >
		<div id='forminner-view'>

		</div>
		<div class='split-line'></div>

		<div id='comment_list' class='mchide'>
			<h1>留言</h1>
			<ul class='list-unstyled'>
			</ul>
			<script type='text/template' id='comment_list_item'>
				<li class='' <%=id%>>
					<div class='col-lg-10 wrapper'>
						<div class='content col-lg-12'>
							<div class='content col-lg-12'>
								<%=content%>
							</div>
						</div>
						<div class='subject col-lg-12'>
							<span class='author col-lg-6'><%=uname%> - <%=created %></span>
							<span class='attach col-lg-6'></span>
						</div>
					</div>
					<div class='col-lg-2'>
						<a href='#' class='op delete'><i class='glyphicon glyphicon-remove'></i></a>
					</div>
				</li>
			</script>
		</div>

		<div class='form_board well mchide col-lg-12' style='margin: 10px 0 0 0; padding: 10px 0 5px;'>
			<div class="form-group" >
				<div class="col-lg-10">
					<button type="button" class="btn btn-primary draft mchide">保存草稿</button>
					<button type="button" class="btn btn-warning publish mchide">发布</button>
					<button type="button" class="btn btn-success save mchide">保存</button>
					<button type="button" class="btn btn-info to_dealing mchide">处理中</button>
					<button type="button" class="btn btn-warning to_done mchide">已处理</button>
					<button type="button" class="btn btn-danger to_close mchide">关闭</button>
					<button type="button" class="btn btn-success reopen mchide">重新打开</button>
				</div>
			</div>
			<div class="form-group" style='margin: 0px;'>
				<input class='col-lg-12' name='comment'>
				<div class=''>
					<div class='pull-left'>
						<a href='#' class='icon-selector' data-toggle='popover' data-placement='top' ><img src='/img/smile.png' width='16' style='position: relative; top: -3px;'/></a>
						<div class='popover mchide'>
							<div class='icon-wrapper'>
								<?php echo Comment\Comment::showAll( 24 ); ?>
							</div>
						</div>
						<a href='#' style='position: relative; top: 3px;' ><span id="do-comment-img">building...</span></a>
					</div>
					<div class='pull-right'>
						<button type="button" class="btn comment">评论</button>
					</div>
				</div>
			</div>
		</div>
	</form>
</div>
<script>
var time_point_list = ['7天以内', '8-30天', '30天-1年', '1年以上']
var huanhuo_reason_list = ['个人原因', '价格原因', '产品原因', '物流原因', '发货原因', '发票原因']	
</script>
<script type='text/template' id='template-formview-2-12'>
<div class='mission-form-inner'>
	<div>
		<h1 class='col-lg-6'>#<%= (typeof(id) == 'undefined' || id <= 0) ? '新建任务' : id %> - 退还补发 - 换货</h1>
		<div class='col-lg-6 pull-right' style='margin: 20px 0 10px; color: red; text-align: right; ' >客服：<%= kf_state_name %><%= cg_state ? '&nbsp;&nbsp;仓管：' + cg_state_name : '' %>
		</div>
	</div>
	<div class='state' style='clear:both;'>
		<ul class='list-inline'>
			<li><label>发起人：</label><%=create_uname%><%= create_uid == kf_uid ? '' : ' => ' + kf_uname %></li>
			<li><label>发起时间：</label><%=created%></li>
		</ul>
	</div>

	<div class='split-line'></div>

	<input type='hidden' name='mission_type_id' value='<%=mission_type_id%>' />

	<div class="form-group">
		<label class="col-lg-2" >店铺：</label>
		<div class='col-lg-4'>
			<select name='store_id' class='col-lg-10' class='store' ></select>
		</div>
		<label class="col-lg-2" for="ipt_wanwan">旺旺：</label>
		<div class='col-lg-4'>
			<input type="text" name='wanwan' class="form-control wanwan" value='<%=wanwan%>'
				id='ipt_wanwan' placeholder="">
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >订单号：</label>
		<div class='col-lg-10'>
			<input type="text" name='order_num' class="form-control" value='<%=order_num_list%>'
				placeholder="多个订单号用空格分开">
			<div class='help-block'>多个订单号用空格分开</div>
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >时间点：</label>
		<div class='col-lg-10'>
			<select name='time_point' class='col-lg-4' >
				<% _.each(time_point_list, function(val,key) { if( !time_point ) time_point = key %>
					<option value='<%= val %>' <%= typeof(time_point) != 'undefined' && time_point == val ? 'selected' : '' %>><%= val %></option> <% }); %>
			</select>
			<div class='checkbox'>
				<label>
			    	<input type="checkbox" name='earlier_send' <%= ( typeof( earlier_send ) != 'undefined' && 
			    		'on' == earlier_send ) ? 'checked' : '' %> 提前发货
			    </label>
			</div>
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >换货原因：</label>
		<div class='col-lg-10'>
			<select name='huanhuo_reason' class='col-lg-4' >
				<% _.each(huanhuo_reason_list, function(val,key) { if( !huanhuo_reason ) huanhuo_reason = key %>
					<option value='<%= val %>' <%= typeof(huanhuo_reason) != 'undefined' && huanhuo_reason == val ? 'selected' : '' %>><%= val %></option> <% }); %>
			</select>
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >具体原因：</label>
		<div class='col-lg-10'>
			<textarea name='detail_reason' class='col-lg-12' rows='2' ><%=detail_reason%></textarea>
		</div>
	</div>

	<div class='split-line'></div>

	<div class="form-group">
		<label class="col-lg-2" >寄回单号：</label>
		<div class='col-lg-10'>
			<input type="text" name='mail_back_num' class="form-control" value='<%=mail_back_num%>'
				 placeholder="">
		</div>
	</div>

	<div class="form-group clearfix">
		<label class="col-lg-2" >原产品：</label>
		<div class='col-lg-10'>
			<select class='col-lg-3' name='send_back_category_id' >
				<% category_id = 0; _.each(category_list, function(val,key) { if( !category_id ) category_id = key %>
					<option value='<%= val.id %>' <%= typeof(category_id) != 'undefined' && category_id == val.category_id ? 'selected' : '' %>>
					<%= val.name %></option> <% }); %>
			</select>
			<select class='col-lg-3' name='send_back_product_id'>
				<% product_id = 0; _.each(product_list[category_id], function(val,key) { %>
					<option value='<%= val.id %>' <%= typeof(product_id) != 'undefined' && product_id == val.product_id ? 'selected' : '' %>>
					<%= val.name %></option> <% }); %>
			</select>
			<input name='send_back_cnt' value='1' style='width: 40px;' />
			<button type="button" class='btn btn-success add_send_back_product'>
				<i class='glyphicon glyphicon-plus'></i> 增加
			</button>
			<table class='table list_send_back_product' style='width: 74%'>
			<tbody></tbody></table>
		</div>
	</div>

	<div class='split-line'></div>

	<div class="form-group">
		<label class="col-lg-2" >寄出单号：</label>
		<div class='col-lg-10'>
			<input type="text" name='mail_to_num' class="form-control" value='<%=mail_to_num%>'
				 placeholder="">
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >地址：</label>
		<div class='col-lg-10'>
			<input type="text" name='mail_to_address' class="form-control" value='<%=mail_to_address%>'
				 placeholder="">
		</div>
	</div>

	<div class="form-group clearfix">
		<label class="col-lg-2" >换出产品：</label>
		<div class='col-lg-10'>
			<select class='col-lg-3' name='send_to_category_id' >
				<% category_id = 0; _.each(category_list, function(val,key) { if( !category_id ) category_id = key %>
					<option value='<%= val.id %>' <%= typeof(category_id) != 'undefined' && category_id == val.category_id ? 'selected' : '' %>>
					<%= val.name %></option> <% }); %>
			</select>
			<select class='col-lg-3' name='send_to_product_id'>
				<% product_id = 0; _.each(product_list[category_id], function(val,key) { %>
					<option value='<%= val.id %>' <%= typeof(product_id) != 'undefined' && product_id == val.product_id ? 'selected' : '' %>>
					<%= val.name %></option> <% }); %>
			</select>
			<input name='send_to_cnt' value='1' style='width: 40px;' />
			<button type="button" class='btn btn-success add_send_to_product'>
				<i class='glyphicon glyphicon-plus'></i> 增加
			</button>
			<table class='table list_send_to_product'>
			<tbody></tbody></table>
		</div>
	</div>

	<div class='split-line'></div>

	<div class="form-group fold-controller profit">
		<label class="col-lg-12" >获取利润：
			<i class='dofold glyphicon glyphicon-chevron-up'></i>
			<i class='dounfold glyphicon glyphicon-chevron-down'></i>
		</label>
	</div>
	<div class='fold-content mchide'>
		<div class="form-group">
			<label class="col-lg-2" >利润金额：</label>
			<div class='col-lg-6'>
				<div class="input-group">
					<input placeholder='' class='col-lg-12' name='profit' value='<%=profit %>' />
					<span class="input-group-addon">元</span>
				</div>
			</div>
		</div>
		<div class="form-group">
			<label class="col-lg-2" >利润原因：</label>
			<div class='col-lg-10'>
				<textarea class='col-lg-12' name='profit_reason' rows='2' ><%=profit_reason %></textarea>
			</div>
		</div>
	</div>

	<br/>

	<div class="form-group fold-controller drawback">
		<label class="col-lg-12">开启返现：
			<i class='dofold glyphicon glyphicon-chevron-up'></i>
			<i class='dounfold glyphicon glyphicon-chevron-down'></i>
		</label>
	</div>
	<div class='fold-content mchide'>
		<div class="form-group">
			<label class="col-lg-2" >返现金额：</label>
			<div class="input-group col-lg-3">
				<input placeholder='' class='col-lg-12' name='drawback' value='<%=drawback %>' />
				<span class="input-group-addon">元</span>
			</div>
			<label class="col-lg-2" >支付宝：</label>
			<input placeholder='' class='col-lg-5' name='drawback_zhifubao' value='<%=drawback_zhifubao %>' />
		</div>
		<div class="form-group">
			<label class="col-lg-2" >返现原因：</label>
			<div class='col-lg-10'>
				<textarea class='col-lg-12' name='drawback_reason' rows='2' ><%=drawback_reason %></textarea>
			</div>
		</div>
	</div>
	
</div>
</script>

<script type='text/template' id='template-formview-2-12-add-product-back'>
	<tr>
		<td>
			<input type='hidden' name='send_product_back[<%=uid%>][id]' value='<%=uid%>'/>
			<input type='hidden' name='send_product_back[<%=uid%>][category_id]' value='<%=category_id%>'/>
			<input type='hidden' name='send_product_back[<%=uid%>][product_id]' value='<%=product_id%>'/>
			<input type='hidden' name='send_product_back[<%=uid%>][cnt]' value='<%=cnt%>'/>
			<input type='hidden' name='send_product_back[<%=uid%>][state]' value='<%=state%>'/>
			<%=category%>	
		</td>
		<td><%=product%></td>
		<td><%=cnt%></td>
		<td><a href='#' class='op delete'><i class='glyphicon glyphicon-remove'></i></a></td>
	</tr>
</script>

<script type='text/template' id='template-formview-2-12-add-product-to'>
	<tr>
		<td>
			<input type='hidden' name='send_product_to[<%=uid%>][id]' value='<%=uid%>'/>
			<input type='hidden' name='send_product_to[<%=uid%>][category_id]' value='<%=category_id%>'/>
			<input type='hidden' name='send_product_to[<%=uid%>][product_id]' value='<%=product_id%>'/>
			<input type='hidden' name='send_product_to[<%=uid%>][cnt]' value='<%=cnt%>'/>
			<input type='hidden' name='send_product_to[<%=uid%>][state]' value='<%=state%>'/>
			<%=category%>	
		</td>
		<td><%=product%></td>
		<td><%=cnt%></td>
		<td><a href='#' class='op delete'><i class='glyphicon glyphicon-remove'></i></a></td>
	</tr>
</script>



<script type='text/template' id='template-formview-2-12-closed'>
<div class='mission-form-inner'>
	<div>
		<h1 class='col-lg-6'>#<%= (typeof(id) == 'undefined' || id <= 0) ? '新建任务' : id %> - 退还补发 - 换货</h1>
		<div class='col-lg-6 pull-right' style='margin: 20px 0 10px; color: red; text-align: right; ' >客服：<%= kf_state_name %><%= cg_state ? '&nbsp;&nbsp;仓管：' + cg_state_name : '' %>
		</div>
	</div>
	<div class='state' style='clear:both;'>
		<ul class='list-inline'>
			<li><label>发起人：</label><%=create_uname%><%= create_uid == kf_uid ? '' : ' => ' + kf_uname %></li>
			<li><label>发起时间：</label><%=created%></li>
		</ul>
	</div>

	<div class='split-line'></div>

	<input type='hidden' name='mission_type_id' value='<%=mission_type_id%>' />

	<div class="form-group">
		<label class="col-lg-2" >店铺：</label>
		<div class='col-lg-4'>
			<%=store%>
		</div>
		<label class="col-lg-2" for="ipt_wanwan">旺旺：</label>
		<div class='col-lg-4'>
			<%=wanwan%>
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >订单号：</label>
		<div class='col-lg-10'>
			<%=order_num_list%>
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >时间点：</label>
		<div class='col-lg-10'>
			<%=time_point%><%= ( typeof( earlier_send ) != 'undefined' && 'on' == earlier_send ) ? ' - 提前发货' : '' %>
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >换货原因：</label>
		<div class='col-lg-10'>
			<%=huanhuo_reason%>	
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >具体原因：</label>
		<div class='col-lg-10'>
			<%=detail_reason%>
		</div>
	</div>

	<div class='split-line'></div>

	<div class="form-group">
		<label class="col-lg-2" >寄回单号：</label>
		<div class='col-lg-10'>
			<%=mail_back_num%>
		</div>
	</div>

	<div class="form-group clearfix">
		<label class="col-lg-2" >原产品：</label>
		<div class='col-lg-10'>
			<table class='table list_send_back_product' style='width: 74%'>
				<% if( 'undefined' != typeof(send_back_product_list) ){ _.each(send_back_product_list, function(val,key) { %>
					<tr>
						<td><%=val.category%></td>
						<td><%=val.product%></td>
						<td><%=val.cnt%></td>
					</tr>
				<% });} %>
			<tbody></tbody></table>
		</div>
	</div>

	<div class='split-line'></div>

	<div class="form-group">
		<label class="col-lg-2" >寄出单号：</label>
		<div class='col-lg-10'>
			<%=mail_to_num%>
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >地址：</label>
		<div class='col-lg-10'>
			<%=mail_to_address%>
		</div>
	</div>

	<div class="form-group clearfix">
		<label class="col-lg-2" >换出产品：</label>
		<div class='col-lg-10'>
			<table class='table list_send_to_product'>
			<tbody>
				<% if( 'undefined' != typeof(send_to_product_list) ){ _.each(send_to_product_list, function(val,key) { %>
					<tr>
						<td><%=val.category%></td>
						<td><%=val.product%></td>
						<td><%=val.cnt%></td>
					</tr>
				<% });} %>
			</tbody></table>
		</div>
	</div>

	<div class='split-line'></div>

	<div class="form-group fold-controller profit unfold">
		<label class="col-lg-12" >获取利润：
		</label>
	</div>
	<div class='fold-content'>
		<div class="form-group">
			<label class="col-lg-2" >利润金额：</label>
			<div class='col-lg-6'>
				<%=profit %><span class="">元</span>
			</div>
		</div>
		<div class="form-group">
			<label class="col-lg-2" >利润原因：</label>
			<div class='col-lg-10'>
				<%=profit_reason %>
			</div>
		</div>
	</div>

	<br/>

	<div class="form-group fold-controller drawback unfold">
		<label class="col-lg-12">开启返现：
		</label>
	</div>
	<div class='fold-content'>
		<div class="form-group">
			<label class="col-lg-2" >返现金额：</label>
			<div class="input-group col-lg-3">
				<%=drawback %><span class="">元</span>
			</div>
			<label class="col-lg-2" >支付宝：</label>
			<%=drawback_zhifubao %>
		</div>
		<div class="form-group">
			<label class="col-lg-2" >返现原因：</label>
			<div class='col-lg-10'>
				<%=drawback_reason %>
			</div>
		</div>
	</div>
	
</div>
</script>
