<?php use Helper\Html ?>
<div class='list-item'>
	<h1>待处理</h1>
	<div class="tab-pane fade active in" id="listitem-1" >
		<?php echo $controller->renderPartial( 'mission/list-table', array( 
			'type'=>1, 'list'=>$controller->waiting_list ) ); ?>
	</div>
</div>
<div class='list-item'>
	<h1>处理中</h1>
	<div class="tab-pane fade in" id="listitem-2">
		<?php echo $controller->renderPartial( 'mission/list-table', array( 
			'type'=>2, 'list'=>$controller->dealing_list ) ); ?>
	</div>
</div>
<div class='list-item'>
	<h1>已处理</h1>
	<div class="tab-pane fade in" id="listitem-3">
		<?php echo $controller->renderPartial( 'mission/list-table', array( 
			'type'=>3, 'list'=>$controller->done_list ) ); ?>
	</div>
</div>
<div class='list-item'>
	<h1>已关闭</h1>
	<div class="tab-pane fade in" id="listitem-4">
		<?php echo $controller->renderPartial( 'mission/list-table', array( 
			'type'=>4, 'list'=>$controller->closed_list ) ); ?>
	</div>
</div>
