<?php use Helper\Html ?>
<div class="" style='margin: 10px 0px; ' id='analyse-wrapper'>
	<ul id="myTab" class="nav nav-tabs">
		<li class="active"><a href="#total" data-toggle="tab">概况</a></li>
		<li class=""><a href="#person" data-toggle="tab">个人统计</a></li>
		<li class='pull-right'>
		</li>
	</ul>
	<div id="myTabContent" class="tab-content">
		<div class="tab-pane fade active in" id="total">
			<?php echo $controller->renderPartial( 'mission/_filter', array( 'type'=>'all' ) ) ?>
			<div class='all-wrapper'>
			</div>
		</div>
		<div class="tab-pane fade" id="person">
			<?php echo $controller->renderPartial( 'mission/_filter', array( 'type'=>'person' ) ) ?>
			<div class='person-wrapper'>
			</div>
		</div>
	</div>
</div>

<script>
var category_list = <?php echo json_encode( CategoryModel::getSelectList() ) ?>; 
var product_list = <?php echo json_encode( ProductModel::getSelectList() ) ?>; 
var mission_type_list = <?php echo json_encode( rbac\MissionType::getMissionTypeList() ) ?>; 

var analyse_filter = {
	time: '', 
	from: '',
	to: '',
	category: 0, 
	product: 0, 
	mission_category: 0, 
	mission_sub_category: 0
};

pageBind.product = function(){
	seajs.use( '/src/admin/analyse');
}
</script>