<div class='success bs-callout bs-callout-success mchide' >
	保存成功
</div>
<div id='form-inner'>
</div>
<script type='text/template' id='cate-template'>
	<h1 class='title'><%= title%></h1>
	<form class="form-horizontal product-form" role="form">
		<div class="form-group">
			<label for="inputEmail1" class="col-lg-2 control-label">类目名</label>
			<div class="col-lg-10">
				<input type="text" class="form-control" id="inputEmail1" name='name' value='<%= name%>'
					placeholder="类目名字">
			</div>
		</div>
		<div class="form-group">
			<div class="col-lg-offset-2 col-lg-10">
				<button type="submit" class="btn btn-default save">保存</button>
			</div>
		</div>
	</form>
</script>
<script type='text/template' id='product-template'>
	<h1 class='title'>新增产品</h1>
	<form class="form-horizontal product-form" role="form">
		<div class="form-group">
			<label for="inputEmail1" class="col-lg-2 control-label">产品名</label>
			<div class="col-lg-10">
				<input type="text" class="form-control" id="inputEmail1" name='name' value='<%= name%>'=
					placeholder="产品名字">
			</div>
		</div>
		<div class="form-group">
			<label for="inputPassword1" class="col-lg-2 control-label">类目</label>
			<div class="col-lg-10">
				<select class='category' class="form-control" name='category_id'>
					<% _.each(category_list, function(val,key) { %>
						<option value='<%= val.id %>' <%= typeof(category_id) != 'undefined' && category_id == val.id ? 'selected' : '' %>>
					<%= val.name %></option> <% }); %>
				</select>
			</div>
		</div>
		<div class="form-group">
			<div class="col-lg-offset-2 col-lg-10">
				<button type="submit" class="btn btn-default save">保存</button>
			</div>
		</div>
	</form>
</script>
