<ul id="form-tool-bar" class="nav nav-tabs">
	<li class="active list-toggller-1"><a href="#form-tab-info" data-toggle="tab">任务详情
		<span class='cnt'></span></a></li>
	<li class="list-toggller-2"><a href="#form-tab-history" data-toggle="tab">操作记录
		<span class='cnt'></span></a></li>
	<li class='pull-right'>
		<ul class='pull-right list-inline'>
			<?php if( $controller->user->role_id == UserModel::ROLE_KF ){ ?>
				<li><a href='#' class='mission-type-change' data-toggle="tooltip" data-placement="bottom" title="" data-original-title="更改任务类型"><i class='glyphicon glyphicon-cog'></i></a></li>
			<?php }?>

			<?php if( $controller->user->role_id == UserModel::ROLE_DZ ){ ?>
				<li><a href='#' class='mission-type-flag' data-toggle="tooltip" data-placement="bottom" title="" data-original-title="插旗"><i class='glyphicon glyphicon-flag'></i></a></li>
			<?php }?>

			<li><a class='form-refresh' href='#' data-toggle="" data-placement="bottom" title="" data-original-title="刷新"><i class='glyphicon glyphicon-refresh'></i></a></li>
		</ul>
	</li>
</ul>

<div id="myTabContent" class="tab-content">
	<div class="tab-pane fade active in" id="form-tab-info">
		<form class="form form-horizontal" role="form" >
			<div id='forminner-view'>
			</div>
			<div class='split-line'></div>
			<?php echo $controller->renderPartial( 'mission/_form_board_and_comment' ) ?>
		</form>
	</div>
	<div class="tab-pane fade" id="form-tab-history">
		<div id='front-history'>
		</div>
	</div>
</div>