<div class="form-group fold-controller profit unfold">
	<label class="col-lg-12" >获取利润：
	</label>
</div>
<div class='fold-content'>
	<div class="form-group">
		<label class="col-lg-2" >利润金额：</label>
		<div class='col-lg-6'>
			<%=profit %><span class="">元</span>
		</div>
	</div>
	<div class="form-group">
		<label class="col-lg-2" >利润原因：</label>
		<div class='col-lg-10'>
			<%=profit_reason %>
		</div>
	</div>
</div>
