<div class="form-group fold-controller profit">
	<label class="col-lg-12" >获取利润：
		<i class='dofold glyphicon glyphicon-chevron-up'></i>
		<i class='dounfold glyphicon glyphicon-chevron-down'></i>
	</label>
</div>
<div class='fold-content mchide'>
	<div class="form-group">
		<label class="col-lg-2" >利润金额：</label>
		<div class='col-lg-6'>
			<div class="input-group">
				<input placeholder='' class='col-lg-12' name='profit' value='<%=profit %>' />
				<span class="input-group-addon">元</span>
			</div>
		</div>
	</div>
	<div class="form-group">
		<label class="col-lg-2" >利润原因：</label>
		<div class='col-lg-10'>
			<textarea class='col-lg-12' name='profit_reason' rows='2' ><%=profit_reason %></textarea>
		</div>
	</div>
</div>