<div class="form-group fold-controller drawback unfold">
	<label class="col-lg-12">开启返现：
	</label>
</div>
<div class='fold-content'>
	<div class="form-group">
		<label class="col-lg-2" >返现金额：</label>
		<div class="input-group col-lg-3">
			<%=drawback %><span class="">元</span>
		</div>
		<label class="col-lg-2" >支付宝：</label>
		<%=drawback_zhifubao %>
	</div>
	<div class="form-group">
		<label class="col-lg-2" >返现原因：</label>
		<div class='col-lg-10'>
			<%=drawback_reason %>
		</div>
	</div>
</div>
