<?php if( $controller->user->role_id == UserModel::ROLE_KF ){ ?>

	<div class="form-group fold-controller drawback">
		<label class="col-lg-12">开启返现：
			<i class='dofold glyphicon glyphicon-chevron-up'></i>
			<i class='dounfold glyphicon glyphicon-chevron-down'></i>
		</label>
	</div>
	<div class='fold-content mchide'>
		<div class="form-group">
			<label class="col-lg-2" >返现金额：</label>
			<div class="input-group col-lg-3">
				<input placeholder='' class='col-lg-12' name='drawback[money]' value='<%=drawback %>' />
				<span class="input-group-addon">元</span>
			</div>
			<label class="col-lg-2" >支付宝：</label>
			<input placeholder='' class='col-lg-5' name='drawback[zhifubao]' value='<%=drawback_zhifubao %>' />
		</div>
		<div class="form-group">
			<label class="col-lg-2" >返现原因：</label>
			<div class='col-lg-10'>
				<textarea class='col-lg-12' name='drawback[reason]' rows='2' ><%=drawback_reason %></textarea>
			</div>
		</div>
	</div>

	<% if( user_state != 0 && app_data.user.role_id == 1 ){ %>
	<div class="form-group mchide drawback_controller drawback_state_<%= typeof( drawback_state ) != 'undefined' ? drawback_state : 'none' %>" >
		<label class="col-lg-2" >返现状态：</label>
		<div class='col-lg-10 '>
			<span style='color: <%= drawback_state == 3 ? 'green': 'red' %>'>
				<%=drawback_state_name %>
			</span>
			<div class='pull-right'>
				<a class='do-drawback word-btn word-btn-danger'>确认返现</a>
				<a class='do-drawback-cancel word-btn word-btn-warning'>取消返现</a>
			</div>
		</div>
	</div>
	<% } %>

<?php }else{

	echo $controller->renderPartial( 'mission/_form_drawback_closed' );
}?>