
<div>
	<h1 class='col-lg-6'>#<%= (typeof(id) == 'undefined' || id <= 0) ? '新建任务' : id %> - <?php echo $name ?></h1>
	<div class='col-lg-6 pull-right' style='margin: 20px 0 10px; color: red; text-align: right; ' >
		<%= kf_state ? '&nbsp;&nbsp;客服：' + kf_state_name : '' %>
		<% if( state != 2 && app_data.user.role_id == 2 && kf_state == 4 ){ %>
			<a class='word-btn word-btn-warning btn-reopen-cg'>打开</a>
		<% } %>
		<%= cg_state ? '&nbsp;&nbsp;仓管：' + cg_state_name : '' %>
		<% if( state != 2 && app_data.user.role_id == 1 && cg_state == 4 ){ %>
			<a class='word-btn word-btn-warning btn-reopen-kf'>打开</a>
		<% } %>
	</div>
</div>
<div class='state' style='clear:both;'>
	<ul class='list-inline'>
		<li><label>发起人：</label><%=create_uname%><%= create_uid == kf_uid ? '' : ' => ' + kf_uname %></li>
		<li><label>发起时间：</label><%=created%></li>
	</ul>
</div>

<div class='split-line'></div>