<div class='success bs-callout bs-callout-success mchide' >
	保存成功
</div>
<div id='forminner-mission'>
	<div id='forminner-view'>
	</div>
</div>
<script type='text/template' id='template-formview-1-7'>
<div class='mission-form-inner'>
	<h1>新建任务 - 订单修改 - 订单与发货不符合</h1>

	<form class="form form-horizontal" role="form" >

		<input type='hidden' name='id' value='<%=id%>' />
		<input type='hidden' name='mission_type_id' value='<%=mission_type_id%>' />

		<div class="form-group">
			<label class="col-lg-2" for="ipt_order_num">店铺：</label>
			<div class='col-lg-4'>
				<input type="text" name='store' class="form-control store" value='<%=store%>'
					id='ipt_store' placeholder="">
			</div>
			<label class="col-lg-2" for="ipt_wanwan">旺旺：</label>
			<div class='col-lg-4'>
				<input type="text" name='wanwan' class="form-control wanwan" value='<%=wanwan%>'
					id='ipt_wanwan' placeholder="">
			</div>
		</div>

		<div class="form-group">
			<label class="col-lg-2" for="ipt_order_num">订单号：</label>
			<div class='col-lg-10'>
				<input type="text" name='order_num' class="form-control" value='<%=order_num%>'
					id="ipt_order_num" placeholder="多个订单号用空格分开">
				<div class='help-block'>多个订单号用空格分开</div>
			</div>
		</div>
		<div class="form-group clearfix">
			<label class="col-lg-2" for="ipt_order_num">发货产品：</label>
			<div class='col-lg-10'>
				<select name='send_category_id' class='col-lg-3' name='category_id' >
					<% category_id = 0; _.each(category_list, function(val,key) { if( !category_id ) category_id = key %>
						<option value='<%= val.id %>' <%= typeof(category_id) != 'undefined' && category_id == val.category_id ? 'selected' : '' %>>
						<%= val.name %></option> <% }); %>
				</select>
				<select name='send_product_id' class='col-lg-3' name='product_id'>
					<% _.each(product_list[category_id], function(val,key) { %>
						<option value='<%= val.id %>' <%= typeof(product_id) != 'undefined' && product_id == val.product_id ? 'selected' : '' %>>
						<%= val.name %></option> <% }); %>
				</select>
				<input name='send_cnt' value='1' style='width: 40px;' />
				<button type="button" class='btn btn-success add-product'>
					<i class='glyphicon glyphicon-plus'></i> 增加
				</button>
				<table class='table list-product'>
				<tbody></tbody></table>
			</div>
		</div>
		<div class="form-group">
			<label class="col-lg-2" for="ipt_order_num">发货地址：</label>
			<div class='col-lg-10'>
				<textarea placeholder='每行一个地址' class='col-lg-12' rows='2' name='address'><%=address%></textarea>
			</div>
		</div>
		<div class="form-group">
			<label class="col-lg-2" for="ipt_order_num">备注：</label>
			<div class='col-lg-10'>
				<textarea placeholder='' class='col-lg-12' rows='3' name='comment'><%=comment%></textarea>
			</div>
		</div>
		<div class="form-group">
			<div class="col-lg-offset-2 col-lg-10">
				<button type="button" class="btn btn-primary draft">保存草稿</button>
				<button type="submit" class="btn btn-warning publish">发布</button>
			</div>
		</div>
	</form>
</div>
</script>
<script type='text/template' id='template-formview-1-17-add-product'>
	<tr>
		<td>
			<input type='hidden' name='send_product[<%=uid%>][cateogory_id]' value='<%=category_id%>'/>
			<input type='hidden' name='send_product[<%=uid%>][product_id]' value='<%=product_id%>'/>
			<input type='hidden' name='send_product[<%=uid%>][cnt]' value='<%=cnt%>'/>
			<%=category%>	
		</td>
		<td><%=product%></td>		
		<td><%=cnt%></td>
		<td><a href='#' class='op delete'><i class='glyphicon glyphicon-remove'></i></a></td>
	</tr>
</script>
