<div id='forminner-mission-1-11'>
	<?php echo $controller->renderPartial( 'mission/_form_html' ); ?>
</div>
<script type='text/template' id='template-formview-1-11'>
<div class='mission-form-inner'>

	<?php echo $controller->renderPartial( 'mission/_template_formview_header', array( 'name'=>$controller->form_name ) ) ?>

	<input type='hidden' name='mission_type_id' value='<%=mission_type_id%>' />

	<div class="form-group">
		<label class="col-lg-2" >店铺：</label>
		<div class='col-lg-4'>
			<select name='store_id' class='col-lg-10' class='store' ></select>
		</div>
		<label class="col-lg-2" for="ipt_wanwan">旺旺：</label>
		<div class='col-lg-4'>
			<input type="text" name='wanwan' class="form-control wanwan" value='<%=wanwan%>'
				id='ipt_wanwan' placeholder="">
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >订单号：</label>
		<div class='col-lg-10'>
			<input type="text" name='order_num' class="form-control" value='<%=order_num_list%>'
				placeholder="多个订单号用空格分开">
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" for="">姓名：</label>
		<div class='col-lg-10'>
			<input type="text" name='realname' class="form-control" value='<%=realname%>'
				placeholder="">
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" for="">身份证：</label>
		<div class='col-lg-10'>
			<input type="text" name='person_id' class="form-control" value='<%=person_id%>'
				placeholder="">
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" for="">手机：</label>
		<div class='col-lg-10'>
			<input type="text" name='mobile' class="form-control" value='<%=mobile%>'
				placeholder="">
		</div>
	</div>

</div>
</script>

<?php echo $controller->renderPartial( 'mission/form-1-11-closed' ) ?>
