<div id='forminner-mission-3-18'>
	<?php echo $controller->renderPartial( 'mission/_form_html' ); ?>
</div>
<script type='text/template' id='template-formview-3-18'>
<div class='mission-form-inner'>
	
	<?php echo $controller->renderPartial( 'mission/_template_formview_header', array( 'name'=>$controller->form_name ) ) ?>

	<input type='hidden' name='mission_type_id' value='<%=mission_type_id%>' />

	<div class="form-group">
		<label class="col-lg-2" >店铺：</label>
		<div class='col-lg-4'>
			<select name='store_id' class='col-lg-10' class='store' ></select>
		</div>
		<label class="col-lg-2" for="ipt_wanwan">旺旺：</label>
		<div class='col-lg-4'>
			<input type="text" name='wanwan' class="form-control wanwan" value='<%=wanwan%>'
				id='ipt_wanwan' placeholder="">
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >订单号：</label>
		<div class='col-lg-10'>
			<input type="text" name='order_num' class="form-control" value='<%=order_num_list%>'
				placeholder="多个订单号用空格分开">
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >快递单号：</label>
		<div class='col-lg-10'>
			<input type="text" name='mail_to_num' class="form-control" value='<%=mail_to_num%>'
				placeholder="">
		</div>
	</div>

	<?php echo $controller->renderPartial( 'mission/_form_product_html', array( 'type'=>'old', 'name'=>'产品' ) ); ?>

	<div class="form-group">
		<label class="col-lg-2" >具体描述：</label>
		<div class='col-lg-10'>
			<textarea name='detail_description' class="col-lg-12" rows='3'
				><%=detail_description%></textarea>
		</div>
	</div>

</div>
</script>

<?php echo $controller->renderPartial( 'mission/_form_product' ) ?>
<?php echo $controller->renderPartial( 'mission/form-3-18-closed' ) ?>
