<div id='forminner-mission-2-16'>
	<?php echo $controller->renderPartial( 'mission/_form_html' ); ?>
</div>
<script type='text/template' id='template-formview-2-16'>
<div class='mission-form-inner'>
	
	<?php echo $controller->renderPartial( 'mission/_template_formview_header', array( 'name'=>$controller->form_name ) ) ?>

	<input type='hidden' name='mission_type_id' value='<%=mission_type_id%>' />

	<div class="form-group">
		<label class="col-lg-2" >店铺：</label>
		<div class='col-lg-4'>
			<select name='store_id' class='col-lg-10' class='store' ></select>
		</div>
		<label class="col-lg-2" for="ipt_wanwan">旺旺：</label>
		<div class='col-lg-4'>
			<input type="text" name='wanwan' class="form-control wanwan" value='<%=wanwan%>'
				id='ipt_wanwan' placeholder="">
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >订单号：</label>
		<div class='col-lg-10'>
			<input type="text" name='order_num' class="form-control" value='<%=order_num_list%>'
				placeholder="多个订单号用空格分开">
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >发票类型：</label>
		<div class='col-lg-10'>
			<select name='receipt' class='col-lg-4' >
				<% _.each(receipt_list, function(val,key) { if( !receipt ) receipt = key %>
					<option value='<%= val %>' <%= typeof(receipt) != 'undefined' && receipt == val ? 'selected' : '' %>><%= val %></option> <% }); %>
			</select>
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >抬头：</label>
		<div class='col-lg-10'>
			<input name='receipt_subject' class='col-lg-12' value='<%=receipt_subject%>' />
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >税号：</label>
		<div class='col-lg-10'>
			<input name='receipt_num' class='col-lg-12' value='<%=receipt_num%>' />
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >金额: </label>
		<div class='col-lg-10'>
			<input name='receipt_money' class='col-lg-12' value='<%=receipt_money%>' />
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >其他信息：</label>
		<div class='col-lg-10'>
			<input name='receipt_other' class='col-lg-12' value='<%=receipt_other%>' placeholder='如增票信息' />
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >补寄地址：</label>
		<div class='col-lg-10'>
			<input name='receipt_address' class='col-lg-12' value='<%=receipt_address%>' />
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >具体原因：</label>
		<div class='col-lg-10'>
			<textarea name='detail_reason' class='col-lg-12' rows='3' ><%=detail_reason%></textarea>
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >寄出单号：</label>
		<div class='col-lg-10'>
			<input type="text" name='receipt_mail_to_num' class="form-control" value='<%=receipt_mail_to_num%>'
				 placeholder="">
		</div>
	</div>

	<div class='split-line'></div>

	<?php echo $controller->renderPartial( 'mission/_form_profit' ) ?>

	<br/>

	<?php echo $controller->renderPartial( 'mission/_form_drawback' ) ?>

</div>
</script>

<?php echo $controller->renderPartial( 'mission/_form_product' ) ?>
<?php echo $controller->renderPartial( 'mission/form-2-16-closed' ) ?>
