<script type='text/template' id='template-formview-closed-3-18'>
<div class='mission-form-inner'>
	
	<?php echo $controller->renderPartial( 'mission/_template_formview_header', array( 'name'=>$controller->form_name ) ) ?>

	<div class="form-group">
		<label class="col-lg-2" >店铺：</label>
		<div class='col-lg-4'>
			<%=store%>
		</div>
		<label class="col-lg-2" for="ipt_wanwan">旺旺：</label>
		<div class='col-lg-4'>
			<%=wanwan%>
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >订单号：</label>
		<div class='col-lg-10'>
			<%=order_num_list%>
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >快递单号：</label>
		<div class='col-lg-10'>
			<%=mail_to_num%>
		</div>
	</div>

	<?php echo $controller->renderPartial( 'mission/_form_product_closed', array( 'type'=>'old', 'name'=>'产品' ) ); ?>

	<div class="form-group">
		<label class="col-lg-2" >具体描述：</label>
		<div class='col-lg-10'>
			<%=detail_description%>
		</div>
	</div>

</div>
</script>
