<div id='forminner-mission-1-8'>
	<form class="form form-horizontal" role="form" >
		<div id='forminner-view'>

		</div>
		<div class='split-line'></div>

		<?php echo $controller->renderPartial( 'mission/_form_board_and_comment' ) ?>

	</form>
</div>
<script type='text/template' id='template-formview-1-8'>
<div class='mission-form-inner'>

	<?php echo $controller->renderPartial( 'mission/_template_formview_header', array( 'name'=>$controller->form_name ) ) ?>

	<input type='hidden' name='mission_type_id' value='<%=mission_type_id%>' />

	<div class="form-group">
		<label class="col-lg-2" >店铺：</label>
		<div class='col-lg-4'>
			<select name='store_id' class='col-lg-10' class='store' ></select>
		</div>
		<label class="col-lg-2" for="ipt_wanwan">旺旺：</label>
		<div class='col-lg-4'>
			<input type="text" name='wanwan' class="form-control wanwan" value='<%=wanwan%>'
				id='ipt_wanwan' placeholder="">
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >订单号：</label>
		<div class='col-lg-10'>
			<input type="text" name='order_num' class="form-control" value='<%=order_num_list%>'
				placeholder="">
			<div class='help-block'></div>
		</div>
	</div>
	
	<div class="form-group">
		<label class="col-lg-2" for="ipt_order_num">备注：</label>
		<div class='col-lg-10'>
			<textarea placeholder='' class='col-lg-12' rows='3' name='remarks'><%=remarks%></textarea>
		</div>
	</div>
	
</div>
</script>

<?php echo $controller->renderPartial( 'mission/form-1-8-closed' ) ?>
