<div id='forminner-mission-1-9'>
	<form class="form form-horizontal" role="form" >
		<div id='forminner-view'>

		</div>
		<div class='split-line'></div>

		<?php echo $controller->renderPartial( 'mission/_form_board_and_comment' ) ?>

	</form>
</div>
<script type='text/template' id='template-formview-1-9'>
<div class='mission-form-inner'>

	<?php echo $controller->renderPartial( 'mission/_template_formview_header', array( 'name'=>$controller->form_name ) ) ?>

	<input type='hidden' name='mission_type_id' value='<%=mission_type_id%>' />

	<div class="form-group">
		<label class="col-lg-2" >店铺：</label>
		<div class='col-lg-4'>
			<select name='store_id' class='col-lg-10' class='store' ></select>
		</div>
		<label class="col-lg-2" for="ipt_wanwan">旺旺：</label>
		<div class='col-lg-4'>
			<input type="text" name='wanwan' class="form-control wanwan" value='<%=wanwan%>'
				id='ipt_wanwan' placeholder="">
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >订单号：</label>
		<div class='col-lg-10'>
			<input type="text" name='order_num' class="form-control" value='<%=order_num_list%>'
				placeholder="">
			<div class='help-block'></div>
		</div>
	</div>
	<div class="form-group clearfix">
		<label class="col-lg-2" for="ipt_order_num">退货产品：</label>
		<div class='col-lg-10'>
			<select class='col-lg-3' name='send_to_category_id' >
				<% category_id = 0; _.each(category_list, function(val,key) { if( !category_id ) category_id = key %>
					<option value='<%= val.id %>' <%= typeof(category_id) != 'undefined' && category_id == val.category_id ? 'selected' : '' %>>
					<%= val.name %></option> <% }); %>
			</select>
			<select class='col-lg-3' name='send_to_product_id'>
				<% product_id = 0; _.each(product_list[category_id], function(val,key) { %>
					<option value='<%= val.id %>' <%= typeof(product_id) != 'undefined' && product_id == val.product_id ? 'selected' : '' %>>
					<%= val.name %></option> <% }); %>
			</select>
			<input name='send_to_cnt' value='1' style='width: 40px;' />
			<button type="button" class='btn btn-success add_send_to_product'>
				<i class='glyphicon glyphicon-plus'></i> 增加
			</button>
			<table class='table list_send_to_product'>
			<tbody></tbody></table>
		</div>
	</div>
	<div class="form-group">
		<label class="col-lg-2" for="ipt_order_num">退款原因：</label>
		<div class='col-lg-10'>
			<textarea placeholder='' class='col-lg-12' rows='2' name='refundment_reason'><%=refundment_reason%></textarea>
		</div>
	</div>

	<div class='split-line'></div>

	<?php echo $controller->renderPartial( 'mission/_form_refundment' ) ?>

	<?php echo $controller->renderPartial( 'mission/_form_profit' ) ?>

</div>
</script>

<?php echo $controller->renderPartial( 'mission/_form_product' ) ?>
<?php echo $controller->renderPartial( 'mission/form-1-9-closed' ) ?>
