<div id='forminner-mission-5-20'>
	<?php echo $controller->renderPartial( 'mission/_form_html' ); ?>
</div>
<script type='text/template' id='template-formview-5-20'>
<div class='mission-form-inner'>
	
	<?php echo $controller->renderPartial( 'mission/_template_formview_header', array( 'name'=>$controller->form_name ) ) ?>

	<input type='hidden' name='mission_type_id' value='<%=mission_type_id%>' />

	<div class="form-group">
		<label class="col-lg-2" >姓名：</label>
		<div class='col-lg-10'>
			<input type="text" name='realname' class="form-control" value='<%=realname%>' placeholder="">
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >手机：</label>
		<div class='col-lg-10'>
			<input type="text" name='mobile' class="form-control" value='<%=mobile%>' placeholder="">
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >付款金额：</label>
		<div class='col-lg-10'>
			<input type="text" name='pay_money' class="form-control" value='<%=pay_money%>' placeholder="">
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >付款时间：</label>
		<div class='col-lg-10 input-group date'>
			<input class="datepicker" size="16" type="text" 
			value="" name='pay_time' readonly="">
			<span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
		</div>
	</div>

	<?php echo $controller->renderPartial( 'mission/_form_product_html', array( 'type'=>'to', 'name'=>'产品' ) ); ?>

</div>
</script>

<?php echo $controller->renderPartial( 'mission/_form_product' ) ?>
<?php echo $controller->renderPartial( 'mission/form-5-20-closed' ) ?>
