<div id='forminner-mission-6-21'>
	<?php echo $controller->renderPartial( 'mission/_form_html' ); ?>
</div>
<script type='text/template' id='template-formview-6-21'>
<div class='mission-form-inner'>
	
	<?php echo $controller->renderPartial( 'mission/_template_formview_header', array( 'name'=>$controller->form_name ) ) ?>

	<input type='hidden' name='mission_type_id' value='<%=mission_type_id%>' />

	<div class="form-group">
		<label class="col-lg-2" >店铺：</label>
		<div class='col-lg-4'>
			<select name='store_id' class='col-lg-12' class='store' ></select>
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >汇款人：</label>
		<div class='col-lg-10'>
			<input type="text" name='mail_person_name' class="form-control" value='<%=mail_person_name%>' placeholder="">
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >汇款银行：</label>
		<div class='col-lg-10'>
			<input type="text" name='mail_person_bank' class="form-control" value='<%=mail_person_bank%>' placeholder="">
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >所在地：</label>
		<div class='col-lg-10'>
			<input type="text" name='mail_person_bank_address' class="form-control" value='<%=mail_person_bank_address%>' placeholder="">
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >金额：</label>
		<div class='col-lg-10'>
			<input type="text" name='mail_money' class="form-control" value='<%=mail_money%>' placeholder="">
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >付款时间：</label>
		<div class='col-lg-10 input-group date'>
			<input class="datepicker" size="16" type="text" 
			value="" name='mail_time' readonly="">
			<span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >收件信息：</label>
		<div class='col-lg-10'>
			<textarea name='mail_product_info' class="col-lg-12" ><%=mail_product_info%></textarea>
		</div>
	</div>

	<?php echo $controller->renderPartial( 'mission/_form_product_html', array( 'type'=>'to', 'name'=>'产品' ) ); ?>

	<div class="form-group">
		<label class="col-lg-2" >发货单号：</label>
		<div class='col-lg-10'>
			<input type="text" name='mail_address' class="form-control" value='<%=mail_address%>' placeholder="">
		</div>
	</div>

</div>
</script>

<?php echo $controller->renderPartial( 'mission/_form_product' ) ?>
<?php echo $controller->renderPartial( 'mission/form-6-21-closed' ) ?>
