<div id='forminner-mission-1-9'>
	<?php echo $controller->renderPartial( 'mission/_form_html' ); ?>
</div>
<script type='text/template' id='template-formview-1-9'>
<div class='mission-form-inner'>

	<?php echo $controller->renderPartial( 'mission/_template_formview_header', array( 'name'=>$controller->form_name ) ) ?>

	<input type='hidden' name='mission_type_id' value='<%=mission_type_id%>' />

	<div class="form-group">
		<label class="col-lg-2" >店铺：</label>
		<div class='col-lg-4'>
			<select name='store_id' class='col-lg-10' class='store' ></select>
		</div>
		<label class="col-lg-2" for="ipt_wanwan">旺旺：</label>
		<div class='col-lg-4'>
			<input type="text" name='wanwan' class="form-control wanwan" value='<%=wanwan%>'
				id='ipt_wanwan' placeholder="">
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >订单号：</label>
		<div class='col-lg-10'>
			<input type="text" name='order_num' class="form-control" value='<%=order_num_list%>'
				placeholder="">
			<div class='help-block'></div>
		</div>
	</div>

	<?php echo $controller->renderPartial( 'mission/_form_product_html', array( 'type'=>'back', 'name'=>'退货产品' ) ); ?>

	<div class="form-group">
		<label class="col-lg-2" for="ipt_order_num">退款原因：</label>
		<div class='col-lg-10'>
			<textarea placeholder='' class='col-lg-12' rows='2' name='refundment_reason'><%=refundment_reason%></textarea>
		</div>
	</div>

	<div class='split-line'></div>

	<?php echo $controller->renderPartial( 'mission/_form_refundment' ) ?>

	<?php echo $controller->renderPartial( 'mission/_form_profit' ) ?>

</div>
</script>

<?php echo $controller->renderPartial( 'mission/_form_product' ) ?>
<?php echo $controller->renderPartial( 'mission/form-1-9-closed' ) ?>
