
<script type='text/template' id='template-formview-closed-2-12'>
<div class='mission-form-inner'>
	
	<?php echo $controller->renderPartial( 'mission/_template_formview_header', array( 'name'=>$controller->form_name ) ) ?>

	<div class="form-group">
		<label class="col-lg-2" >店铺：</label>
		<div class='col-lg-4'>
			<%=store%>
		</div>
		<label class="col-lg-2" for="ipt_wanwan">旺旺：</label>
		<div class='col-lg-4'>
			<%=wanwan%>
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >订单号：</label>
		<div class='col-lg-10'>
			<%=order_num_list%>
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >时间点：</label>
		<div class='col-lg-10'>
			<%=time_point%><%= ( typeof( earlier_send ) != 'undefined' && 'on' == earlier_send ) ? ' - 提前发货' : '' %>
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >换货原因：</label>
		<div class='col-lg-10'>
			<%=huanhuo_reason%>	
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >具体原因：</label>
		<div class='col-lg-10'>
			<%=detail_reason%>
		</div>
	</div>

	<div class='split-line'></div>

	<div class="form-group">
		<label class="col-lg-2" >寄回单号：</label>
		<div class='col-lg-10'>
			<%=mail_back_num%>
		</div>
	</div>

	<div class="form-group clearfix">
		<label class="col-lg-2" >原产品：</label>
		<div class='col-lg-10'>
			<table class='table list_send_back_product'>
				<% if( 'undefined' != typeof(send_back_product_list) ){ _.each(send_back_product_list, function(val,key) { %>
					<tr>
						<td><%=val.category%></td>
						<td><%=val.product%></td>
						<td><%=val.cnt%></td>
						<td><%=val.state_name%></td>
					</tr>
				<% });} %>
			<tbody></tbody></table>
		</div>
	</div>

	<div class='split-line'></div>

	<div class="form-group">
		<label class="col-lg-2" >寄出单号：</label>
		<div class='col-lg-10'>
			<%=mail_to_num%>
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >地址：</label>
		<div class='col-lg-10'>
			<%=mail_to_address%>
		</div>
	</div>

	<div class="form-group clearfix">
		<label class="col-lg-2" >换出产品：</label>
		<div class='col-lg-10'>
			<table class='table list_send_to_product'>
			<tbody>
				<% if( 'undefined' != typeof(send_to_product_list) ){ _.each(send_to_product_list, function(val,key) { %>
					<tr>
						<td><%=val.category%></td>
						<td><%=val.product%></td>
						<td><%=val.cnt%></td>
						<td><%=val.state_name%></td>
					</tr>
				<% });} %>
			</tbody></table>
		</div>
	</div>

	<div class='split-line'></div>

	<?php echo $controller->renderPartial( 'mission/_form_profit_closed' ) ?>

	<br/>

	<?php echo $controller->renderPartial( 'mission/_form_drawback_closed' ) ?>

</div>
</script>
