
<script type='text/template' id='template-formview-closed-1-8'>
<div class='mission-form-inner'>

	<?php echo $controller->renderPartial( 'mission/_template_formview_header', array( 'name'=>$controller->form_name ) ) ?>

	<div class="form-group">
		<label class="col-lg-2" >店铺：</label>
		<div class='col-lg-4'>
			<%=store%>
		</div>
		<label class="col-lg-2" for="ipt_wanwan">旺旺：</label>
		<div class='col-lg-4'>
			<%=wanwan%>
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" >订单号：</label>
		<div class='col-lg-10'>
			<%=order_num_list%>
		</div>
	</div>

	<div class="form-group">
		<label class="col-lg-2" for="ipt_order_num">备注：</label>
		<div class='col-lg-10'>
			<%=remarks%>
		</div>
	</div>

</div>
</script>
