<h1><?php echo $category ?> - <?php echo $sub_category ?> - #<?php echo $model->id ?></h1>
<div class='state'>
	<ul class='list-inline'>
		<li><label>发起人：</label><?php echo $create_uname ?><?php echo $model->create_uid == $model->kf_uid ? '' : ' => '. $kf_uname ?></li>
		<li><label>发起时间：</label><?php echo $created ?></li>
	</ul>
</div>

<div id='history'>
	<table class='table'>
		<thead>
			<tr>
				<th>修改内容</th>
				<th>修改人</th>
				<th>时间</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach( $history as $key=>$history_one ) { ?>
				<?php if( count( $history ) > 1 && count( $history_one > 0 ) ){ ?>
					<tr class='mission-one-title'>
						<td >
							<h1><?php echo $key ?></h1>
						</td>
						<td></td>
						<td></td>
					</tr>
				<?php } ?>
				<?php foreach( $history_one as $one ){ ?>
					<tr>
						<td><ul class='list-unstyled'>
							<?php 
							$changed = json_decode( $one['changed'], true );
							if( $changed ){
								foreach( $changed as $one1 ){ 
									$action = MissionChangeLogModel::getAction( $one1 );
									$value = MissionChangeLogModel::getValue( $one1 );
								?>
									<li style='word-wrap: break-word; white-space: normal;'><?php echo '【'. $action. '】'. $one1['key']. ' - '. $value ?></li>
								<?php }
							}
							?>
						</ul></td>
						<td><?php echo UserModel::getName( $one['uid'] )?></td>
						<td><?php echo Helper\Html::date( $one['created'] )?></td>
					</tr>
				<?php } ?>
			<? } ?>
		</tbody>
	</table>
</div>