<div id="layout">
    <div class='layout-message-outer mchide'>
    </div>
    <div class='layout-message-inner mchide'>
        <div class='layout-success bs-callout bs-callout-success mchide' style='margin: 0px;'>
            保存成功
        </div>
        <div class='layout-message bs-callout bs-callout-info mchide' style='margin: 0px;'>
        </div>
    </div>
    <div class='row'>
        <div class='col-2 border' id='front-menu'>
            <?php echo $this->render( 'layouts/menu.phtml', array( 'controller'=>$controller ) ) ?>
        </div>
        <div class='col-10' id='front-body'>
            <div class='row'>
            	<div class='col-6 border' id='front-list'>
            		<?php $this->display( 'mission/list.phtml', array( 'controller'=>$controller ) ); ?>
            	</div>
            	<div class='col-6' id='front-form'>
            		<?php $this->display( 'mission/form.phtml', array( 'controller'=>$controller ) ); ?>
            	</div>
            </div>
        </div>
    </div>
</div>

<script>
var category_list = <?php echo json_encode( CategoryModel::getSelectList() ) ?>; 
var product_list = <?php echo json_encode( ProductModel::getSelectList() ) ?>; 
var time_point_list = ['7天以内', '8-30天', '30天-1年', '1年以上'];
var huanhuo_reason_list = ['个人原因', '价格原因', '产品原因', '物流原因', '发货原因', '发票原因']; 
var tuihuo_reason_list = ['个人原因', '价格原因', '产品原因', '物流原因', '发货原因', '发票原因']; 
var receipt_list = ['普票', '增票']; 
var sub_mail_type_list = ['产品损坏', '产品漏发', '安抚顾客']; 
pageBind.product = function(){
}
</script>

<div class="modal fade" id="modal-mission-change">
    <div class="modal-dialog">
        <form class='form-inline'>
            <div class="modal-content">
                <?php echo Helper\Html::authToken() ?>
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"
                        aria-hidden="true">&times;</button>
                    <h4 class="modal-title">配置管理</h4>
                </div>
                <div class="modal-body">
                    <div>
                        <ul class="nav nav-tabs" id="myTab">
                            <?php 
                            $mission_type_list = rbac\Role::getRoleActions( $controller->user->role_id );
                            $first = true; foreach( $mission_type_list as $one ) { ?>
                                <li class="<?php echo $first ? 'active' : '' ?>">
                                    <a href="#mission-type-<?php echo $one['data']['id'] ?>" 
                                        data-id='<?php echo $one['data']['id']?>'
                                        data-toggle='tab'
                                        >
                                        <?php echo $one['data']['name'] ?></a></li>
                            <?php $first = false; }?>
                        </ul>
                        <div class="tab-content" style='padding: 10px 0 40px 0;'>
                            <?php $first = true; foreach( $mission_type_list as $one ) { ?>
                                <div class="tab-pane <?php echo $first ? 'active' : '' ?>" 
                                    id="mission-type-<?php echo $one['data']['id']?>">
                                    <?php 
                                    sort( $one['children'] );
                                    $children = $one['children'];
                                    foreach( $children as $one1 ){ 
                                        ?>
                                        <input class="btn btn-xs btn-default" type="button" value="<?php echo $one1['name'] ?>" 
                                        data-id='<?php echo $one1['id'] ?>'>
                                    <?php } ?>
                                </div>
                            <?php $first = false; }?>
                        </div>
                        <div class='form-group'>
                            <input type='button' class='btn btn-xs btn-primary btn-change-type' value='更改任务类型' />
                        </div>
                    </div>
                    <div class='split-line'></div>
                    <div>
                        <div class='form-group'>
                            <select class='select kefu-uid' style='width: 100px;'>
                                <?php $list = UserModel::getKefuList(); 
                                foreach( $list as $one ){  
                                    if( $one['id'] == $controller->user->id )continue;
                                ?>
                                    <option value='<?php echo $one['id'] ?>'><?php echo $one['name'] ?></option>
                                <?php }?>
                            </select>
                            <input type='button' class='btn btn-xs btn-primary btn-change-kefu' value='交接' />
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>


<div class="modal fade" id="modal-mission-flag">
    <div class="modal-dialog">
        <form class='form-inline' onsubmit='return false;'>
            <div class="modal-content">
                <?php echo Helper\Html::authToken() ?>
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"
                        aria-hidden="true">&times;</button>
                    <h4 class="modal-title">插旗子</h4>
                </div>
                <div class="modal-body">
                    <div class='form-group'>
                        <label class='checkbox'>
                            <input type='checkbox' class='checkbox' value='<?php echo MissionFlagModel::MIST_KF ?>' name='mistake[]' />
                            客服失误
                        </label>
                        <label class='checkbox'>
                            <input type='checkbox' class='checkbox' value='<?php echo MissionFlagModel::MIST_CG ?>' name='mistake[]' />
                            仓管失误
                        </label>
                        <label class='checkbox'>
                            <input type='checkbox' class='checkbox' value='<?php echo MissionFlagModel::MIST_CK ?>' name='mistake[]' />
                            仓库失误
                        </label>
                        <label class='checkbox'>
                            <input type='checkbox' class='checkbox' value='<?php echo MissionFlagModel::MIST_OTHER ?>' name='mistake[]' />
                            其他情况
                        </label>
                    </div>
                    <div class='form-group'>
                        <textarea class='textarea col-lg-12' rows='7' name='remarks' ></textarea>
                    </div>
                </div>
                <div class="modal-footer" style='clear: both;'>
                    <input type="button" class="btn btn-xs btn-primary" value='保存'>
                </div>
            </div>
        </form>
    </div>
</div>

