<div id="layout">
    <div class='row'>
        <div class='col-2 border' id='front-menu'>
            <?php echo $this->render( 'layouts/menu.phtml', array( 'controller'=>$controller ) ) ?>
        </div>
        <div class='col-10' id='front-body'>
            <div class='row'>
            	<div class='col-6 border' id='front-list'>
            		<?php $this->display( 'mission/list.phtml', array( 'controller'=>$controller ) ); ?>
            	</div>
            	<div class='col-6' id='front-form'>
            		<?php $this->display( 'mission/form.phtml', array( 'controller'=>$controller ) ); ?>
            	</div>
                <div class='col-6 mc-hide' id='front-history'>
                </div>
                <div class='col-6' >
                    
                </div>
            </div>
        </div>
    </div>
</div>

<script>
var category_list = <?php echo json_encode( CategoryModel::getSelectList() ) ?>; 
var product_list = <?php echo json_encode( ProductModel::getSelectList() ) ?>; 
var time_point_list = ['7天以内', '8-30天', '30天-1年', '1年以上'];
var huanhuo_reason_list = ['个人原因', '价格原因', '产品原因', '物流原因', '发货原因', '发票原因']; 
pageBind.product = function(){
}
</script>

<div class="modal fade" id="modal-mission-change">
    <div class="modal-dialog">
        <form class='form-inline'>
            <div class="modal-content">
                <?php echo Helper\Html::authToken() ?>
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"
                        aria-hidden="true">&times;</button>
                    <h4 class="modal-title">更改任务类型</h4>
                </div>
                <div class="modal-body">
                    <input type='hidden' name='mission_id' value='' />
                    <div class='form-group'>
                        <select class='select-cate'>
                        </select>
                    </div>
                    <div class='form-group'>
                        <select class='select-subcate'>
                        </select>
                    </div>
                    <div class='form-group '>
                        <input type='button' class='btn btn-primary btn-mission-change' value='更改' />
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="button" class="btn btn-primary" value='更改'>
                </div>
            </div>
        </form>
    </div>
</div>