<?php use Helper\Html ?>

<?php switch( $controller->user->role_id ){
	case UserModel::ROLE_DZ: ?>

		<ul id="myTab" class="nav nav-tabs">
			<li class="active list-toggller-1"><a href="#listitem-6" data-toggle="tab">待返现
				<span class='cnt'></span></a></li>
			<li class="list-toggller-2"><a href="#listitem-7" data-toggle="tab">待退款
				<span class='cnt'></span></a></li>
			<li class="list-toggller-8"><a href="#listitem-8" data-toggle="tab">未关闭
				<span class='cnt'></span></a></li>
			<li class="list-toggller-9"><a href="#listitem-9" data-toggle="tab">已关闭
				<span class='cnt'></span></a></li>
			<li class='pull-right'>
				<ul class='pull-right list-inline'>
					<li><a class='word-btn word-btn-success batch-submit'>提交</a></li>
					<li><a class='list-refresh' href='#' data-toggle="" data-placement="bottom" title="" data-original-title="刷新"><i class='glyphicon glyphicon-refresh'></i></a></li>
				</ul>
			</li>
		</ul>

		<div id="myTabContent" class="tab-content">
			<div class="tab-pane fade active in" id="listitem-6" data-type='6'>
				<?php echo $controller->renderPartial( 'mission/list-table-batch', array( 
					'type'=>6, 'list'=>$controller->waiting_list_drawback ) ); ?>
			</div>
			<div class="tab-pane fade in" id="listitem-7" data-type='7'>
				<?php echo $controller->renderPartial( 'mission/list-table-batch', array( 
					'type'=>7, 'list'=>$controller->waiting_list_refundment ) ); ?>
			</div>
			<div class="tab-pane fade in" id="listitem-8" data-type='8'>
				<?php echo $controller->renderPartial( 'mission/list-table', array( 
					'type'=>8, 'list'=>$controller->unclosed_list ) ); ?>
			</div>
			<div class="tab-pane fade in" id="listitem-9" data-type='9'>
				<?php echo $controller->renderPartial( 'mission/list-table', array( 
					'type'=>9, 'list'=>$controller->closed_list ) ); ?>
			</div>
		</div>

	<?php break;
	case UserModel::ROLE_FCG: ?>
		
	<?php break;
	default: ?>

		<ul id="myTab" class="nav nav-tabs">
			<li class="active list-toggller-1"><a href="#listitem-1" data-toggle="tab">待处理
				<span class='cnt'></span></a></li>
			<li class="list-toggller-2"><a href="#listitem-2" data-toggle="tab">处理中
				<span class='cnt'></span></a></li>
			<li class="list-toggller-3"><a href="#listitem-3" data-toggle="tab">已处理
				<span class='cnt'></span></a></li>
			<li class="list-toggller-4"><a href="#listitem-4" data-toggle="tab">已关闭
				<span class='cnt'></span></a></li>
			<li class='pull-right'>
				<ul class='pull-right list-inline'>
					<li><a class='list-refresh' href='#' data-toggle="" data-placement="bottom" title="" data-original-title="刷新"><i class='glyphicon glyphicon-refresh'></i></a></li>
				</ul>
			</li>
		</ul>

		<div id="myTabContent" class="tab-content">
			<div class="tab-pane fade active in" id="listitem-1" data-type='1'>
				<?php echo $controller->renderPartial( 'mission/list-table', array( 
					'type'=>1, 'list'=>$controller->waiting_list ) ); ?>
			</div>
			<div class="tab-pane fade in" id="listitem-2" data-type='2'>
				<?php echo $controller->renderPartial( 'mission/list-table', array( 
					'type'=>2, 'list'=>$controller->dealing_list ) ); ?>
			</div>
			<div class="tab-pane fade in" id="listitem-3" data-type='3'>
				<?php echo $controller->renderPartial( 'mission/list-table', array( 
					'type'=>3, 'list'=>$controller->done_list ) ); ?>
			</div>
			<div class="tab-pane fade in" id="listitem-4" data-type='4'>
				<?php echo $controller->renderPartial( 'mission/list-table', array( 
					'type'=>4, 'list'=>$controller->closed_list ) ); ?>
			</div>
		</div>
	<?php 
		break;
} ?>