<?php $user = $controller->user; ?>
<table class='table table-hover'>
	<thead>
		<tr>
			<th class=''>#</th>
			<th class='col1'>状态</th>
			<th class=''>类型</th>
			<th class='col-3'>订单号</th>
			<th class='col-2'>旺旺ID</th>
			<th class='col-1'>店铺</th>
			<th class='col-2'>修改时间</th>
			<th class='' style='width: 5%;'></th>
		</tr>
	</thead>
	<tbody>
		<?php
		foreach( $list as $one ){?>
			<tr data-type='<?php echo $type?>' id='listitem-<?=$one['id']?>' cate-id='<?=$one['category_id']?>' 
				sub-cate-id='<?=$one['sub_category_id']?>'>
				<td><?=$one['id']?></td>
				<td class='mission_state'><?=$one['mission_state']?></td>
				<td><?=$one['sub_category']?></td>
				<td><?=isset( $one['order_num_list'] ) ? implode( "<br/>", $one['order_num_list'] ): ''?></td>
				<td><?=$one['wanwan']?></td>
				<td><?=StoreModel::getName( $one['store_id'] )?></td>
				<td><?=Helper\Html::date( $one['created'] )?></td>
				<td>
					<a href='#' class='op edit mchide'><i class='glyphicon glyphicon-chevron-right'></i></a>
				</td>
			</tr>
		<?php }?>
	</tbody>
	<script type='text/template' id='template-<?php echo $type?>-listitem'>
		<tr data-type='<?php echo $type ?>' id='listitem-<%=id%>' cate-id='<%=category_id%>' 
				sub-cate-id='<%=sub_category_id%>'>
			<td><%=id%></td>
			<td class='mission_state'><%=mission_state%></td>
			<td><%=sub_category%></td>
			<td><%=order_num_list%></td>
			<td><%=wanwan%></td>
			<td><%=store%></td>
			<td><%=created%></td>
			<td>
				<a href='#' class='op edit mchide'><i class='glyphicon glyphicon-chevron-right'></i></a>
			</td>
		</tr>
	</script>
</table>