<?php $user = $controller->user; ?>
<table class='table table-hover'>
	<thead>
		<tr>
			<th class=''><input type='checkbox' class='checkbox checkall' /></th>
			<th class=''>#</th>
			<th class='col1'>状态</th>
			<th class=''>类型</th>
			<th class='col-2'>旺旺ID</th>
			<th class='col-2'>支付宝</th>
			<th class=''>金额</th>
			<th class='col-2'>修改时间</th>
			<th class='' style='width: 5%;'></th>
		</tr>
	</thead>
	<tbody>
		<?php
		foreach( $list as $one ){?>
			<tr data-type='<?php echo $type?>' id='listitem-<?=$one['id']?>' cate-id='<?=$one['category_id']?>' 
				sub-cate-id='<?=$one['sub_category_id']?>'>
				<td><input type='checkbox' class='checkbox' name='' value='<?php echo $one['id'] ?>' /></td>
				<td><?=$one['id']?></td>
				<td class='mission_state'><?=$one['mission_state']?></td>
				<td><?=$one['sub_category']?></td>
				<td><?=$one['wanwan']?></td>
				<td><?=isset( $one['drawback_zhifubao'] ) ? $one['drawback_zhifubao'] : ''?></td>
				<td><?=isset( $one['drawback_money'] ) ? $one['drawback_money'] : ''?></td>
				<td><?=Helper\Html::date( $one['created'] )?></td>
				<td>
					<a href='#' class='op edit mchide'><i class='glyphicon glyphicon-chevron-right'></i></a>
				</td>
			</tr>
		<?php }?>
	</tbody>
	<script type='text/template' id='template-<?php echo $type?>-listitem'>
		<tr data-type='<?php echo $type ?>' id='listitem-<%=id%>' cate-id='<%=category_id%>' 
				sub-cate-id='<%=sub_category_id%>'>
			<td><input type='checkbox' class='checkbox' name='batch[]' value='<%= id %>' /></td>
			<td><%=id%></td>
			<td class='mission_state'><%=mission_state%></td>
			<td><%=sub_category%></td>
			<td><%=wanwan%></td>
			<td><%=typeof( drawback_zhifubao ) == 'undefined' ? '' : drawback_zhifubao %></td>
			<td><%=typeof( drawback ) == 'undefined' ? '' : drawback %></td>
			<td><%=created%></td>
			<td>
				<a href='#' class='op edit mchide'><i class='glyphicon glyphicon-chevron-right'></i></a>
			</td>
		</tr>
	</script>
</table>