<div class='success bs-callout bs-callout-success mchide' >
	保存成功
</div>
<div id='form-inner'>
</div>
<script type='text/template' id='announce-template'>
	<h1 class='title'><%= title%></h1>
	<form class="form-horizontal announce-form" role="form" style='width: 95%;'>
		<div class="form-group">
			<label for="inputEmail1" class="col-lg-2 control-label">标题：</label>
			<div class="col-lg-10">
				<input type="text" class="form-control" name='subject' value='<%= subject%>'
					placeholder="">
			</div>
		</div>

		<div class="form-group">
			<label for="inputEmail1" class="col-lg-2 control-label">内容：</label>
			<div class="col-lg-10">
				<textarea class="col-lg-12 textarea" rows='10' name='content' id='textarea<%=_.uniqueId() %>'
					placeholder=""><%=content%></textarea>
			</div>
		</div>

		<div class="form-group">
			<div class="col-lg-offset-2 col-lg-10">
				<button type="submit" class="btn btn-default save">保存</button>
			</div>
		</div>
	</form>
</script>