<?php use Helper\Html?>
<!DOCTYPE html>
<head>
        <?= Html::css('/bootstrap/3.0/css/bootstrap.min.css')?>
        <?= Html::css('/bootstrap/3.0/css/bootstrap-glyphicons.css')?>
        <?= Html::css('/bootstrap/3.0/css/docs.css')?>
        <?= Html::css('/css/admin/admin.css')?>
</head>
<body>

<!-- 
  <form>
    <input type='hidden' name='a' value='1' />
    <input name='b' value='1' />
    <input type='checkbox' name='c' value='1' />
    <input type='checkbox' name='c[a]' value='1' />
    <input type='checkbox' name='c[a][1]' value='1' />
    <input type='button' id='abc' value='tijiao' />
  </form> -->

  <?= Html::javascript('/sea-modules/seajs/seajs/2.1.1/sea.js')?>
  <script>
        seajs.config({
          base: "/sea-modules",
          alias: {
            // "$": "/js/jquery-1.10.2.min.js",
            "$": "jquery/jquery/1.10.1/jquery.js",
            "underscore": "gallery/underscore/1.4.4/underscore", 
            "backbone": "gallery/backbone/1.0.0/backbone", 
            "bootstrap": "/bootstrap/3.0/js/bootstrap.min.js"
          }
        })
        // 加载入口模块
        seajs.use(['$', '/html5-notify/desktop-notify'], function( $ ){
            $().ready(function(){
            });
        });
  </script>
</body>
</html>