<?php 
	list( $list, $pager ) = $controller->user->message->getList( $controller->get( 'page', 1 ) ); ?>
<?php if( $list ){ ?>
	<table class='table table-hover'>
		<thead>
			<th>#</th>
			<th>标题</th>
			<th class='col-lg-2'>时间</th>
			<th class='col-lg-1'>操作</th>
		</thead>
	<?php foreach( $list as $one ){ ?>
		<tbody>
			<tr data-id='<?php echo $one['id'] ?>' data-mission-id='<?php echo $one['mission_id']?>' 
    class='<?php echo $one['readed'] ? 'readed' : '' ?>' >
				<td><?php echo $one['id']?></td>
				<td class='subject'>
					<?php echo $one['title']?>
					<div class='content m-hide'>
							<?php echo $one['content']; ?>
					</div>
				</td>
				<td><?php echo Helper\Html::date( $one['created'] ) ?></td>
				<td>
      <a href='#' onclick='' class='op op-remove'><i class='glyphicon glyphicon-remove'></i></a>
					<a href='#' onclick='' class='op op-check-message'><i class='glyphicon glyphicon-eye-open'></i></a>
				</td>
			</tr>
		</tbody>
	<?php }?>
	</table>
	<?php echo $pager->render(); ?>
<?php }?>