<div class="modal fade" id='message-inner'>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">消息</h4>
      </div>
      <div class="modal-body">
        <?php echo $controller->renderPartial( 'message/_page' ); ?>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger pull-left clear-all" >清空</button>
        <button type="button" class="btn btn-success readed-all" >全部已读</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
      </div>
    </div>
  </div>
</div>
<script>
<?php $message = $controller->user->message; ?>
var message_init = {
	cnt: parseInt( '<?php echo $message->new_count ?>' ), 
	list: <?php echo json_encode( $message->new_list ) ?>
}

</script>