
<div class='row' style='padding-top: 20px; ' id='index'>
	<div class='col-lg-4 border' id='index-list' style='height: 1000px;'>
		<div style='clear: both; height: 34px;'>
			<h1 class='pull-left' style='color: #999; font-size: 16px; font-weight: bold; margin: 0px; line-height: 34px;'>公告板</h1>
			<div class='pull-right'>
				<?php if( $controller->user->checkPermission( 'announce' ) ){ ?>
					<!-- <button class='btn btn-normal' onclick='window.open( "/announce" )'>发公告</button> -->
				<?php }?>
			</div>
		</div>
		<table class='table table-hover' style='clear: both; margin-top: 10px;'>
			<thead>
			</thead>
			<tbody>
				<?php list( $announce_list ) = AnnounceModel::getListIndex(); 
				foreach( $announce_list as $one ){ ?>
					<tr id='listitem-announce-<?php echo $one['id']?>' data-id='<?php echo $one['id']?>'>
						<td class='col-lg-1'>【公告】</td>
						<td class=''><?php echo $one['subject'] ?></td>
						<td class='col-lg-1'><?php echo date( 'm月d日', strtotime( $one['created'] ) ) ?></td>
						<td class='col-lg-1'><?php echo Helper\Html::dateOfWeek( $one['created'] ) ?></td>
						<td class='col-lg-1'>
							<a href='#' class='op edit mchide'><i class='glyphicon glyphicon-chevron-right'></i></a>
						</td>
					</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
	<div class='col-lg-8' id='index-content'>
		<div class='content'>
		</div>
	</div>
</div>

<script>
var announce_id = parseInt( '<?php echo $controller->get( 'id', 0 ) ?>' );
pageBind.product = function(){
	seajs.use( '/src/app/index');
}
</script>