
<div class='row' style='padding-top: 20px; ' id='index'>
	<div class='col-lg-4 border' id='index-list' style='height: 1000px;'>
		<div style='clear: both; height: 34px;'>
			<h1 class='pull-left' style='color: #999; font-size: 16px; font-weight: bold; margin: 0px; line-height: 34px;'>公告板</h1>
			<div class='pull-right'>
				<?php if( $controller->user->checkPermission( 'announce' ) ){ ?>
					<!-- <button class='btn btn-normal' onclick='window.open( "/announce" )'>发公告</button> -->
				<?php }?>
			</div>
		</div>
		<div class='announce-wrapper'>
			<?php echo $controller->renderPartial( 'index/_announce_page' ) ?>
		</div>
	</div>
	<div class='col-lg-8' id='index-content'>
		<div class='content'>
		</div>
	</div>
</div>

<script>
var announce_id = parseInt( '<?php echo $controller->get( 'id', 0 ) ?>' );
pageBind.product = function(){
	seajs.use( '/src/app/index');
}
</script>