<div class='row'>
  <div class='col-6 border' id='admin-list'>
    <?php $this->display( 'product/list.phtml', array( 'controller'=>$controller ) ); ?>
  </div>
  <div class='col-6' id='admin-form'>
    <?php $this->display( 'product/form.phtml', array( 'controller'=>$controller ) ); ?>
  </div>
</div>
<script>
var category_list = <?php echo json_encode( CategoryModel::getSelectList() ) ?>;
pageBind.product = function(){
	seajs.use( '/src/admin/product');
}
</script>