<style>
#login input{
	height: 40px;
	line-height: 40px;
}
</style>
<div style='background: #E7EBF2; height: 500px;'>
	<div class="container" id='login'>

		<div class='row' style='margin: 50px 0;'>
			<div class='col-6 text-center'>
				<h2 class="form-signin-heading">合道电器</h2>
			</div>
			<div class='col-6' style=''>

				<form action="" method="post" id="login-form" class="form-signin" 
					style='width: 300px; margin: 0 auto; '>
					<input type="hidden" name="csrfmiddlewaretoken"
						value="e44APAG0Bq2futeBOK16Z31peEPNETac">

					<?php echo Helper\Html::authToken(); ?>
					<?php echo Helper\Html::formMessage( $this ); ?>

					<br/>

					<input type="hidden" name="csrfmiddlewaretoken"
						value="e44APAG0Bq2futeBOK16Z31peEPNETac">
					<div id="div_id_username" class="control-group">
						<div class="controls">
							<input class="textinput textInput" id="id_username" maxlength="254"
								name="username" type="text" placeholder='用户名' />
						</div>
					</div>
					<br/>
					<div id="div_id_password" class="control-group">
						<div class="controls">
							<input class="textinput textInput" id="id_password" name="password"
								type="password" placeholder='密码' />
						</div>
					</div>
					<input id="id_this_is_the_login_form" name="this_is_the_login_form"
						type="hidden" value="1"> <input type="hidden"
						name="this_is_the_login_form" value="1"> <input type="hidden"
						name="next" value="/xadmin/">

					<br/>
					<button class="btn btn-large btn-primary btn-block" type="submit">登录</button>
				</form>
				
			</div>

	</div>
</div>