<div class='success bs-callout bs-callout-success mchide'>保存成功</div>
<div id='form-inner'></div>
<script type='text/template' id='user-template'>
	<h1 class='title'><%= title%></h1>
	<form class="form-horizontal product-form" role="form">
		<div class="form-group">
			<label for="inputEmail1" class="col-lg-2 control-label">姓名</label>
			<div class="col-lg-10">
				<input type="text" class="form-control" id="" name='name' value='<%=name%>'
					placeholder="请输入名字">
			</div>
		</div>
		<div class="form-group">
			<label for="inputEmail1" class="col-lg-2 control-label">用户名（登录用）</label>
			<div class="col-lg-10">
				<input type="text" class="form-control" id="" name='username' value='<%=username%>'
					placeholder="请输入用户名（登录用）">
			</div>
		</div>
		<div class="form-group">
			<label for="inputEmail1" class="col-lg-2 control-label">密码</label>
			<div class="col-lg-10">
				<input type="password" class="form-control" id="" name='pwd' value='<% %>'
					placeholder="请输入密码">
			</div>
		</div>
		<div class="form-group">
			<label for="inputPassword1" class="col-lg-2 control-label">身份</label>
			<div class="col-lg-10">
				<select class='category' class="form-control" name='role_id'>
					<% _.each(role_list, function(val,key) { %>
						<option value='<%= val.id %>' <%= typeof(role_id) != 'undefined' && role_id == val.id ? 'selected' : '' %>>
						<%= val.name %></option>
					<% }); %>
				</select>
			</div>
		</div>
		<div class="form-group">
			<div class="col-lg-offset-2 col-lg-10">
				<button type="submit" class="btn btn-default save">保存</button>
			</div>
		</div>
	</form>
</script>