<?php use Helper\Html?>
<div class="">
	<div>
		<div class='pull-right'>
			<span href="#" class='btn user-create'><i class='glyphicon glyphicon-gift'></i>&nbsp;&nbsp;新建用户</span>
		</div>	
	</div>
	<table class='table table-hover'>
		<thead>
			<tr>
				<th class='col-1'>#</th>
				<th>姓名</th>
				<th class='col-2'>用户名</th>
				<th class='col-2'>身份</th>
				<th class='col-2'>状态</th>
				<th class='col-3'>最近登录</th>
				<th class='col-3'>操作</th>
			</tr>
		</thead>
		<tbody>
				<?php
				$users = $controller->users;
				foreach ( $users as $one ) {
					?>
					<tr class='<?php echo $one['state'] == 101 ? 'baned' : '' ?>' id='listitem-user-<?=$one['id']?>'>
						<td><?=$one['id']?></td>
						<td class='username'><?=$one['username']?></td>
						<td class='name'><?=$one['name']?></td>
						<td class='role_name'><?=$one['role_name']?></td>
						<td class='state_name'><?=$one['state_name']?></td>
						<td><?=Html::date( $one['logined'] )?></td>
						<td>
							<a href='#' class='op ban'><i class='glyphicon glyphicon-ban-circle'></i></a> 
							<a href='#' class='op restore'><i class='glyphicon glyphicon-ok-circle'></i></a> 
							<a href='#' class='op delete'><i class='glyphicon glyphicon-remove'></i></a> 
							<a href='#' class='op edit mchide'><i class='glyphicon glyphicon-chevron-right'></i></a>
						</td>
					</tr>
				<?php }?>
			</tbody>
			<script type='text/template' id='template-user-listitem'>
				<tr class='' id='listitem-user-<%=id%>'>
					<td><%=id%></td>
					<td class='username'><%=username%></td>
					<td class='name'><%=name%></td>
					<td class='role_name'><%=role_name%></td>
					<td class='state_name'><%=state_name%></td>
					<td><%=logined%></td>
					<td>
						<a href='#' class='op ban'><i class='glyphicon glyphicon-ban-circle'></i></a> 
						<a href='#' class='op restore'><i class='glyphicon glyphicon-ok-circle'></i></a> 
						<a href='#' class='op delete'><i class='glyphicon glyphicon-remove'></i></a> 
						<a href='#' class='op edit mchide'><i class='glyphicon glyphicon-chevron-right'></i></a>
					</td>
				</tr>
			</script>
	</table>
</div>