<?php
$tmp = $controller->role_list;
foreach( $tmp as $one ){  
	$list[$one['id']] = $one;
}
?>
<div class='row'>
  <div class='col-6 border' id='admin-list'>
    <?php $this->display( 'user/list.phtml', array( 'controller'=>$controller ) ); ?>
  </div>
  <div class='col-6' id='admin-form'>
    <?php $this->display( 'user/form.phtml', array( 'controller'=>$controller ) ); ?>
  </div>
</div>
<script>
var role_list = <?php echo json_encode( $list ); ?>;
pageBind.product = function(){
	seajs.use( '/src/admin/user');
}
</script>