<div class="bs-sidebar">
	<ul class="nav bs-sidenav">
		<li class=""><a href="/mission"><i class='glyphicon glyphicon-th-list'></i>&nbsp;&nbsp;任务列表</a>
		</li>
		<li class="mission-add-li"><a class='mission-add' href='#' data-toggle='popover' data-placement='right' ><i
				class='glyphicon glyphicon-plus'></i>&nbsp;&nbsp;新建任务</a>
			<div class="popover mchide">
				<div class="arrow"></div>
				<h3 class="popover-title" >新建任务</h3>
				<div class="popover-content" style='width: 500px;'>
					<form class='form-horizantal'>
						<ul class="nav nav-tabs" id="myTab">
							<?php 
							$mission_type_list = rbac\Role::getRoleActions( $controller->user->role_id );
							$first = true; foreach( $mission_type_list as $one ) { ?>
						  		<li class="<?php echo $first ? 'active' : '' ?>">
						  			<a href="#mission-type-<?php echo $one['data']['id'] ?>" 
						  				data-id='<?php echo $one['data']['id']?>'
						  				>
						  				<?php echo $one['data']['name'] ?></a></li>
							<?php $first = false; }?>
						</ul>
						<div class="tab-content" style='padding: 10px 0 40px 0;'>
							<?php $first = true; foreach( $mission_type_list as $one ) { ?>
						  		<div class="tab-pane <?php echo $first ? 'active' : '' ?>" 
						  			id="mission-type-<?php echo $one['data']['id']?>">
						  			<?php 
						  			sort( $one['children'] );
						  			$children = $one['children'];
						  			foreach( $children as $one1 ){ 
						  				?>
						  				<input class="btn btn-default" type="button" value="<?php echo $one1['name'] ?>" 
						  				data-id='<?php echo $one1['id'] ?>'>
						  			<?php } ?>
						  		</div>
							<?php $first = false; }?>
						</div>
						<div class='form-group '>
							<input type='button' class='btn btn-primary btn-mission-add'
								value='创建' /> 
							<input type='button'
								class='btn btn-mission-add-cancel' value='取消' />
						</div>
					</form>
				</div>
			</div></li>
		<li class="<?php echo $controller->nav == 'mission' ? 'active' : ''?>">
			<a class='' href="#"><i
				class='glyphicon glyphicon-th-large'></i>&nbsp;&nbsp;任务查看</a>
			<ul class="nav">
			<?php $list = \rbac\MissionType::getMissionTypeTop(); 
				foreach( $list as $one ){ ?>
				<li class='<?php if( $one['id'] == $controller->subnav )echo 'active'?>' ><a href="/admin/mission/list/id/<?php echo $one['id']?>"><?php echo $one['name']?></a></li>					
			<?php } ?>
			</ul>
		</li>
	</ul>
</div>