<div class="bs-sidebar" style=''>
	<ul class="nav">
		<?php if( $controller->user->role_id == UserModel::ROLE_FCG ){?>

			<li class="<?php echo $controller->nav == 'mission' ? 'tuihuo' : ''?>">
				<a class='' href="/comeback"><i
					class='glyphicon glyphicon-th-large'></i>&nbsp;&nbsp;所有退货
					<i class='glyphicon glyphicon-chevron-right pull-right'></i>
				</a>
			</li>

		<?php }else{?>

			<li class="<?php echo $controller->nav == 'mission' ? 'active' : ''?>">
				<a href="/mission">
					<i class='glyphicon glyphicon-th-list'></i>&nbsp;&nbsp;我的任务
					<i class='glyphicon glyphicon-chevron-right pull-right'></i>
				</a>
			</li>
		<?php }?>

		<?php if( in_array( $controller->user->role_id, array( UserModel::ROLE_FCG, UserModel::ROLE_CG, UserModel::ROLE_DZ ) ) ){ ?>

			<li class="<?php echo $controller->nav == 'announce' ? 'active' : ''?>">
				<a class='mission-add' href='/announce/index' ><i
					class='glyphicon glyphicon-list-alt'></i>&nbsp;&nbsp;公告管理
					<i class='glyphicon glyphicon-chevron-right pull-right'></i>
				</a>
			</li>

		<?php } ?> 

		<?php if( in_array( $controller->user->role_id, array( UserModel::ROLE_FCG, UserModel::ROLE_CG, UserModel::ROLE_DZ ) ) ){ ?>

			<!-- <li class="<?php echo $controller->nav == 'stackout' ? 'active' : ''?>">
				<a class='mission-add' href='/stackout/index' ><i
					class='glyphicon glyphicon-list-alt'></i>&nbsp;&nbsp;缺货管理
					<i class='glyphicon glyphicon-chevron-right pull-right'></i>
				</a>
			</li> -->
		<?php } ?> 


		<?php if( in_array( $controller->user->role_id, array( UserModel::ROLE_CG, UserModel::ROLE_DZ ) ) ){ ?>

			<li class="<?php echo $controller->nav == 'mission' ? 'tuihuo' : ''?>">
				<a class='' href="/comeback"><i
					class='glyphicon glyphicon-th-large'></i>&nbsp;&nbsp;查看退货
					<i class='glyphicon glyphicon-chevron-right pull-right'></i>
				</a>
			</li>

		<?php } ?> 

	</ul>

	<div class='split-line'></div>

	<?php switch( $controller->nav ) {
		case 'mission':
			echo $controller->renderPartial( 'mission/_menu' );
			break;
		default: 
			break;

	}?>

</div>