<header class="">
	<div id="top-bar">
		<div class="row" >
			<div class='col-2 border'>
				<h1 class='logo pull-left'>合道OA</h1>
				<div class='pull-left' style='margin: 15px;'>后台管理</div>
			</div>
			<div class='col-10 border'>
				
				<div class="pull-right" id='menu-user' style='margin: 15px 10px; '>
					<a href='/' >前台</a> | 
					<a href='/admin/login/logout' >注销</a> | 
					<span class='glyphicon glyphicon-question-sign'>&nbsp;&nbsp;</span>
					<a href='#' data-toggle="tooltip" title="lobster-erp" >帮助</a>
				</div>
			</div>
		</div>
	</div>
	<div class='navbar row' id='tool-bar' >
		<div class='col-2 border' style='padding: 0px;'>
			<div class='col-inner'>
				<div class="input-group">
					<span class="input-group-addon"><i class='glyphicon glyphicon-search'></i></span>
					<input id='search-data' name='search' placeholder='请输入单号' />
				</div>
			</div>
		</div>
		<div class='col-10 tool-bar-inner'>
			<div class='col-inner'>
				
			</div>
		</div>
	</div>
</header>