<header class="">
	<div id="top-bar">
		<div class="row" >
			<div class='col-2 border'>
				<h1 class='logo pull-left'>合道OA</h1>
				<div class='pull-left' style='margin: 15px;'>后台管理</div>
			</div>
			<div class='col-5 border'>
				<ul class='list-inline' style='margin: 15px;'>
					<li><a href='/mission'>任务堂</a></li>
					<li><a href='/'>公告板</a></li>
					<li><a href='/tools'>工具箱</a></li>
					<li><a href='http://112.124.17.199:8001/'>合道百科</a></li>
				</ul>
			</div>
			<div class='col-5 row' style='padding-right: 0px;'>
				<div class="pull-right" id='menu-user' style='margin: 15px 10px; '>
					&nbsp;&nbsp;<span class='glyphicon glyphicon-question-sign'></span>
					<a href='#' data-toggle='popover' data-toggle="pop"  data-placement='bottom' >帮助</a> |
					<div class="popover mchide">
						<div>lobster-erp</div>
						<div class='split-line' style='margin: 5px 0'></div>
						<div>monkeycraps</div>
					</div>
					<a href='/' >前台</a> | 
					<a href='/admin/login/logout' >注销</a>
				</div>
			</div>
		</div>
	</div>
<!-- 	<div class='navbar row' id='tool-bar' >
		<div class='col-2 border' style='padding: 0px;'>
			<div class='col-inner'>
				<div class="input-group">
					<span class="input-group-addon"><i class='glyphicon glyphicon-search'></i></span>
					<input id='search-data' name='search' placeholder='请输入单号' />
				</div>
			</div>
		</div>
		<div class='col-10 tool-bar-inner'>
			<div class='col-inner'>
				
			</div>
		</div>
	</div> -->
</header>