<?php
$comeback_list = $controller->comeback_list; 
foreach( $comeback_list as $one ){?>
	<tr class='' id='listitem-comeback-<?=$one['id']?>'>
		<td><?=$one['id']?></td>
		<td class='name'><?=$one['mail_num']?></td>
		<td class='name'><?=$one['product_list']?></td>
		<td class=''><?=$one['result']?></td>
		<td class=''><?=$one['create_uname']?></td>
		<td><?=Helper\Html::date( $one['created'] )?></td>
		<td class=''><?=$one['comment']?></td>
	</tr>
<?php }?>