<div class='success bs-callout bs-callout-success mchide' >
	保存成功
</div>
<div id='form-inner'>
</div>
<script type='text/template' id='comeback-template'>
	<h1 class='title'><%= title%></h1>
	<form class="form-horizontal comeback-form" role="form" style='width: 95%;'>

		<div class="form-group">
			<label for="inputEmail1" class="col-lg-2 control-label">快递公司：</label>
			<div class="col-lg-10">
				<input type="text" class="form-control" name='mail_company' value='<%= mail_company%>'
					placeholder="">
			</div>
		</div>

		<div class="form-group">
			<label for="inputEmail1" class="col-lg-2 control-label">快递号：</label>
			<div class="col-lg-10">
				<input type="text" class="form-control" name='mail_num' value='<%= mail_num%>'
					placeholder="">
			</div>
		</div>

		<div class="form-group">
			<label for="inputEmail1" class="col-lg-2 control-label">产品：</label>
			<div class='col-lg-10'>
				<select class='col-lg-3' name='comeback_category_id' >
					<% category_id = 0; _.each(category_list, function(val,key) { if( !category_id ) category_id = key %>
						<option value='<%= val.id %>' <%= typeof(category_id) != 'undefined' && category_id == val.category_id ? 'selected' : '' %>>
						<%= val.name %></option> <% }); %>
				</select>
				<select class='col-lg-3' name='comeback_product_id'>
					<% product_id = 0; _.each(product_list[category_id], function(val,key) { %>
						<option value='<%= val.id %>' <%= typeof(product_id) != 'undefined' && product_id == val.product_id ? 'selected' : '' %>>
						<%= val.name %></option> <% }); %>
				</select>
				<input name='comeback_product_cnt' value='1' style='width: 40px;' />
				<button type="button" class='btn btn-xs btn-success add_comeback_product'>
					<i class='glyphicon glyphicon-plus'></i> 增加
				</button>
				<table class='table list_comeback_product'>
				<tbody></tbody></table>
			</div>
		</div>

		<div class="form-group">
			<label for="inputEmail1" class="col-lg-2 control-label">检查情况：</label>
			<div class='col-lg-10'>
				<input name='result' value='<%=result%>' />
			</div>
		</div>

		<div class="form-group">
			<label for="inputEmail1" class="col-lg-2 control-label">备注：</label>
			<div class="col-lg-10">
				<textarea class="col-lg-12 textarea" rows='10' name='comment' id='textarea<%=_.uniqueId() %>'
					placeholder=""><%=comment %></textarea>
			</div>
		</div>

		<div class="form-group">
			<div class="col-lg-offset-2 col-lg-10">
				<button type="submit" class="btn btn-default save">保存</button>
			</div>
		</div>
	</form>
</script>

<script type='text/template' id='template-formview-comeback-product'>
	<tr>
		<td>
			<input type='hidden' data-name='id' name='comeback_product[<%=uid%>][id]' value='<%=id%>'/>
			<input type='hidden' data-name='category' name='comeback_product[<%=uid%>][category_id]' value='<%=category_id%>'/>
			<input type='hidden' data-name='product' name='comeback_product[<%=uid%>][product_id]' value='<%=product_id%>'/>
			<input type='hidden' data-name='cnt' name='comeback_product[<%=uid%>][cnt]' value='<%=cnt%>'/>
			<input type='hidden' data-name='state' name='comeback_product[<%=uid%>][state]' value='<%=state%>'/>
			<%=category%>	
		</td>
		<td><%=product%></td>
		<td><%=cnt%></td>
		<td><%=state_name%></td>
		<td class='col-lg-4'>
			<a href='#' class='op delete'><i class='glyphicon glyphicon-remove'></i></	a>
		</td>
	</tr>
</script>
