<?php use Helper\Html ?>
<div class="">
	<ul id="myTab" class="nav nav-tabs">
		<li class="active"><a href="#comeback" data-toggle="tab" data-type='tuihuo'>退货管理</a></li>
		<?php if( $controller->user->role_id == UserModel::ROLE_CG ){ ?>
			<li><a href="#comeback_done" data-toggle="tab" data-type='fanchan'>退货库存</a></li>
		<?php } ?>
		<li class='pull-right'>
		</li>
	</ul>

	<div class="tab-content">
		<div class="tab-pane active" id='comeback'>

			<div class='' style='margin: 10px;height: 25px;'>
				<form onsubmit='return false;' class='pull-left form-inline form-tuihuo'>
					<label>分仓管：</label>
					<select name='fcg' class='form-control'>
						<option value='0'>全部</option>
						<?php $fcg_list = UserModel::getFcgList();
						foreach( $fcg_list as $one ){ ?>
							<option value='<?php echo $one['id'] ?>'><?php echo $one['name']?></option>
						<?php } ?>
					</select>
					<label>状态：</label>
					<select name='state' class='form-control'>
						<option value='0'>全部</option>
						<?php $stateName = ComebackModel::$_stateName;
						foreach( $stateName as $key=>$one ){ ?>
							<option value='<?php echo $key ?>'><?php echo $one ?></option>
						<?php } ?>
					</select>
					<input name='mail_num' placeholder='快递单号' style='width: 300px;' />
					<button class='btn btn-warning btn-xs'>查询</button>
				</form>
			</div>

			<div class='split-line'></div>

			<div class='tuihuo-wrapper'>
				<table class='table table-hover'>
					<thead>
						<tr>
							<th class=''>#</th>
							<th class='col-1'>快递公司</th>
							<th class='col-1'>快递单号</th>
							<th class='col-3'>产品</th>
							<th class='col-1'>登记人</th>
							<th class='col-2'>登记时间</th>
							<th class=''>备注</th>
							<th class=''>状态</th>
							<?php if( $controller->user->role_id == UserModel::ROLE_CG ){ ?>
								<th>操作</th>
							<?php }?>
						</tr>
					</thead>
					<tbody>
						
					</tbody>
				</table>
			</div>
		</div>

			
		<?php if( $controller->user->role_id == UserModel::ROLE_CG ){ ?>
			<div class="tab-pane" id='comeback_done'>

				<div class='' style='margin: 10px;height: 25px;'>

					<form onsubmit='return false;' class='pull-left form-inline form-fanchan'>
						<label>分仓管：</label>
						<select name='fcg' class='form-control'>
							<option value='0'>全部</option>
							<?php $fcg_list = UserModel::getFcgList();
							foreach( $fcg_list as $one ){ ?>
								<option value='<?php echo $one['id'] ?>'><?php echo $one['name']?></option>
							<?php } ?>
						</select>
						<button class='btn btn-warning btn-xs'>查询</button>
					</form>
				</div>

				<div class='split-line'></div>

				<div class='fanchan-wrapper'>
					<table class='table table-hover' style=''>
						<thead>
							<tr>
								<th class='col-1'>产品类型</th>
								<th class='col-1'>型号</th>
								<th class='col-3'>数量</th>
								<th class='col-1'>操作</th>
							</tr>
						</thead>
						<tbody>
							
						</tbody>
					</table>
				</div>

			</div>


		<?php } ?>
	</div>

</div>

<script type='text/template' id='template-comeback-listitem-monitor'>
<tr class='' id='listitem-comeback-<%=id%>'>
	<td><%=id%></td>
	<td><%=mail_company%></td>
	<td class='name'><%=mail_num%></td>
	<td><%=product_list_show%></td>
	<td><%=result%></td>
	<td><%=create_uname%></td>
	<td><%=created%></td>
	<td><%=comment%></td>
	<td><%=state_name%></td>
	<td class='btn-state-<%=state%>'>
		<span class='btn btn-default btn-xs btn-dealwith'>处理</span>
	</td>
</tr>
</script>

