<?php use Helper\Html ?>
<!DOCTYPE html>
<html lang="zh-cn">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>合道电器 - <?php echo $this->title?:null?></title>
        <?= Html::css('/bootstrap/3.0/css/bootstrap.min.css')?>
        <?= Html::css('/bootstrap/3.0/css/bootstrap-glyphicons.css')?>
        <?= Html::css('/bootstrap/3.0/css/docs.css')?>
        <?= Html::css('/css/main.css')?>
    </head>
    <body>
        <?php $this->display( 'layouts/analyticstracking.php', array( 'controller'=>$controller ) ); ?>
        
        <?php $this->display( 'layouts/header.php', array( 'controller'=>$controller ) ); ?>
    	
    	<div class="na" id="layout">
		    <div class="pure-u" id="nav">
                <?php $this->display( 'layouts/menu.php', array( 'controller'=>$controller ) ); ?>
		    </div>
        	<?php echo $_content_;?>
        </div>
        <?php $this->display( 'layouts/modal_list.php', array( 'controller'=>$controller ) ); ?>
        
        <?= Html::javascript('/sea-modules/seajs/seajs/2.1.1/sea.js')?>
        <script>
        // seajs 的简单配置
        seajs.config({
          base: "/sea-modules",
          alias: {
            "$": "/js/jquery-1.10.2.min.js",
            "underscore": "gallery/underscore/1.4.4/underscore", 
            "backbone": "gallery/backbone/1.0.0/backbone", 
            "bootstrap": "/bootstrap/3.0/js/bootstrap.min.js"
          }
        })
        // 加载入口模块
        var app_data = <?php $this->display( 'app_json.php', array( 'controller'=>$controller ) ); ?>;
        seajs.use("$", function(){
            seajs.use("bootstrap")
            seajs.use("/src/app", function(App){
                App.init( app_data );
            })
        });
        </script>
    </body>
</html>