<div class="bs-sidebar">
	<ul class="nav bs-sidenav">
		<li class=""><a href="/mission"><i class='glyphicon glyphicon-th-list'></i>&nbsp;&nbsp;任务列表</a>
		</li>
		<li class="mission-add-li"><a class='mission-add' href='#'><i
				class='glyphicon glyphicon-plus'></i>&nbsp;&nbsp;新建任务</a>
			<div class="popover right mission-add-popover">
				<div class="arrow"></div>
				<h3 class="popover-title">新建任务</h3>
				<div class="popover-content">
					<form class='form-horizantal'>
						<div class='form-group'>
							<select class='select-cate'>
							</select>
						</div>
						<div class='form-group'>
							<select class='select-subcate'>
							</select>
						</div>
						<div class='form-group '>
							<input type='button' class='btn btn-primary btn-mission-add'
								value='创建' /> <input type='button'
								class='btn btn-mission-add-cancel' value='取消' />
						</div>
					</form>
				</div>
			</div></li>
		<!-- 		<li class=""><a href="#btn-groups">Button groups</a> -->
		<!-- 			<ul class="nav"> -->
		<!-- 				<li><a href="#btn-groups-single">Basic button group</a></li> -->
		<!-- 				<li><a href="#btn-groups-toolbar">Button toolbar</a></li> -->
		<!-- 				<li><a href="#btn-groups-vertical">Vertical variation</a></li> -->
		<!-- 				<li><a href="#btn-groups-justified">Justified link buttons</a></li> -->
		<!-- 			</ul></li> -->
	</ul>
</div>